import { useState, useEffect } from "react";
import Table from "../../../components/Table";
import "./co-sales.css";
import { supabase } from "../../../supabase";
import { Download } from "lucide-react";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Tooltip as ChartTooltip,
  Legend,
  Filler,
} from "chart.js";

import { Line } from "react-chartjs-2";
ChartJS.register(
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  ChartTooltip,
  Legend,
  Filler
);

// ==========================================
// EXPORT PDF FUNCTION (kapareho ng design ng Expenses report)
// ==========================================
// PHP ang gamit imbes na ₱ dahil hindi suportado ng default font ng jsPDF ang ₱
const pesoText = (n) =>
  "PHP " +
  Number(n || 0).toLocaleString("en-US", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });

export const exportSalesToPDF = (
  salesData,
  filename = "sales-report.pdf",
  generatedBy = "Co-Associate"
) => {
  const doc = new jsPDF();

  const primaryColor = [30, 41, 59];
  const accentColor = [79, 70, 229];
  const lightBg = [248, 250, 252];

  // Header Design
  doc.setFillColor(...accentColor);
  doc.rect(14, 15, 3, 14, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.setTextColor(...primaryColor);
  doc.text("ADRENALINE AQUA WATER REFILLING STATION", 21, 22);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text("Sales & Revenue Report", 21, 28);

  doc.setFontSize(9);
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, 196, 22, { align: "right" });

  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.4);
  doc.line(14, 34, 196, 34);

  // Summary Box inside PDF
  const totalSalesSum = salesData.reduce(
    (sum, item) => sum + Number(item.total_sales || 0),
    0
  );

  doc.setFillColor(...lightBg);
  doc.roundedRect(14, 40, 182, 14, 1.5, 1.5, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(...primaryColor);
  doc.text(`Total Records: ${salesData.length}`, 18, 49);
  doc.text(`Total Sales: ${pesoText(totalSalesSum)}`, 110, 49);

  // Table Setup
  const tableColumn = ["Sales ID", "Date", "Total Products", "Total Sales", "Payment Method"];
  const tableRows = salesData.map((sale) => [
    sale.sales_code || "-",
    sale.date ? new Date(sale.date).toLocaleDateString() : "-",
    sale.total_products ?? "-",
    pesoText(sale.total_sales),
    sale.payment_method || "-",
  ]);

  autoTable(doc, {
    head: [tableColumn],
    body: tableRows,
    startY: 60,
    theme: "striped",
    headStyles: {
      fillColor: primaryColor,
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 8,
      cellPadding: 6,
    },
    bodyStyles: {
      textColor: [51, 65, 85],
      fontSize: 8,
      cellPadding: 6,
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
    margin: { left: 14, right: 14 },
    didDrawPage: (data) => {
      const pageHeight = doc.internal.pageSize.height;
      doc.setFontSize(8);
      doc.setTextColor(148, 163, 184);
      doc.text(`Generated by: ${generatedBy}`, data.settings.margin.left, pageHeight - 10);
      doc.text(
        `Page ${doc.internal.getNumberOfPages()}`,
        doc.internal.pageSize.width - data.settings.margin.right,
        pageHeight - 10,
        { align: "right" }
      );
    },
  });

  doc.save(filename);
};

export default function CoSales() {
  const [sales, setSales] = useState([]);
  const [monthlySales, setMonthlySales] = useState([]); // State para sa graph
  const [search, setSearch] = useState("");
  const [filter, setFilter] = useState("All");

  useEffect(() => {
    fetchSales();
  }, []);

  const fetchSales = async () => {
    const { data, error } = await supabase
      .from("sales")
      .select("*")
      .order("date", { ascending: false });

    if (error) {
      console.error("Error fetching sales:", error.message);
      return;
    }

    setSales(data || []);

    // LOGIC PARA SA GRAPH (Group by Month)
   const months = [
  "Jan","Feb","Mar","Apr","May","Jun",
  "Jul","Aug","Sep","Oct","Nov","Dec"
];

const grouped = {};

months.forEach(month => {
  grouped[month] = 0;
});

(data || []).forEach((sale) => {
  if (!sale.date) return;

  const month = new Date(sale.date).toLocaleString("en-US", {
    month: "short",
  });

  grouped[month] += Number(sale.total_sales || 0);
});

const graphData = months.map(month => ({
  month,
  sales: grouped[month],
}));

setMonthlySales(graphData);
  };

  const filtered = sales.filter((item) => {
    const matchSearch =
      item.sales_code?.toLowerCase().includes(search.toLowerCase()) ||
      item.staff?.toLowerCase().includes(search.toLowerCase());

    const matchFilter = filter === "All" || item.period === filter;

    return matchSearch && matchFilter;
  });

  const columns = [
    { key: "sales_code", label: "Sales ID" },
    { 
      key: "date", 
      label: "Date", 
      render: (row) => row.date ? new Date(row.date).toLocaleDateString() : "N/A" 
    },
    { key: "total_products", label: "Total Products" },
    { 
      key: "total_sales", 
      label: "Total Sales",
      render: (row) => `₱${Number(row.total_sales || 0).toLocaleString(undefined, {minimumFractionDigits: 2})}` 
    },
    { key: "payment_method", label: "Payment Method" }
  ];

  // EXPORT PDF
  const handleExportPDF = () => {
    if (filtered.length === 0) return;

    let generatedByFull = "Co-Associate";
    try {
      const savedUser = JSON.parse(localStorage.getItem("user")) || {};
      const userPosition = savedUser.position || savedUser.role || "Co-Associate";
      const userName = savedUser.name || savedUser.fullName;
      generatedByFull = userName ? `${userPosition} - ${userName}` : userPosition;
    } catch (err) {
      console.error("Could not read user:", err);
    }

    exportSalesToPDF(
      filtered,
      `sales-report-${new Date().toISOString().split("T")[0]}.pdf`,
      generatedByFull
    );
  };

  // mas maliit na tuldok at text ng graph sa phone
  const isMobile = typeof window !== "undefined" && window.innerWidth <= 600;

  const lineData = {
  labels: monthlySales.map(item => item.month),

  datasets: [
    {
      label: "Monthly Sales",

      data: monthlySales.map(item => item.sales),

      borderColor: "#2563eb",

      backgroundColor: (context) => {
        const chart = context.chart;
        const { ctx, chartArea } = chart;

        if (!chartArea) return null;

        const gradient = ctx.createLinearGradient(
          0,
          chartArea.top,
          0,
          chartArea.bottom
        );

        gradient.addColorStop(0, "rgba(37,99,235,.35)");
        gradient.addColorStop(1, "rgba(147,197,253,0)");

        return gradient;
      },

      fill: true,
      tension: 0.35,

      borderWidth: 3,

      pointStyle: "circle",

      pointRadius: isMobile ? 4 : 7,
      pointHoverRadius: isMobile ? 6 : 10,

      pointBackgroundColor: "#93c5fd",
      pointBorderColor: "#2563eb",
      pointBorderWidth: 2,

      pointHoverBackgroundColor: "#fff",
      pointHoverBorderColor: "#2563eb",
      pointHoverBorderWidth: 3,
    },
  ],
};

const lineOptions = {
  responsive: true,
  maintainAspectRatio: false,

  interaction: {
    mode: "index",
    intersect: false,
  },

  plugins: {
    legend: {
      display: false,
    },

    tooltip: {
      backgroundColor: "#1e293b",
      titleColor: "#fff",
      bodyColor: "#fff",
      padding: 12,
      cornerRadius: 10,

      callbacks: {
        label: (context) =>
          `₱${Number(context.raw).toLocaleString()}`,
      },
    },
  },

 scales: {
  x: {
    grid: {
      display: false,
    },

    ticks: {
      autoSkip: false,     // Ipakita lahat ng buwan
      maxRotation: 0,      // Huwag i-rotate
      minRotation: 0,
      font: {
        size: isMobile ? 9 : 11,
      },
    },
  },

  y: {
    beginAtZero: true,
    ticks: {
      callback: (value) => `₱${value}`,
    },
  },
},
};

  return (
    <div className="cosales-page">
      <div className="cosales-header">
        <h1>Co-Associate Sales</h1>
        <p>View sales performance records</p>
      </div>

      <div className="cosales-controls">
        <input
          type="text"
          className="cosales-search"
          placeholder="Search sales ID or staff..."
          value={search}
          onChange={(e) => setSearch(e.target.value)}
        />
        <select
          className="cosales-filter"
          value={filter}
          onChange={(e) => setFilter(e.target.value)}
        >
          <option value="All">All Periods</option>
          <option value="Daily">Daily</option>
          <option value="Weekly">Weekly</option>
          <option value="Monthly">Monthly</option>
        </select>

        <button
          type="button"
          className="cosales-export-btn"
          onClick={handleExportPDF}
          disabled={filtered.length === 0}
        >
          <Download size={16} /> Export PDF
        </button>
      </div>

      <div className="cosales-table-container">
        <Table
          columns={columns}
          data={filtered}
          emptyMessage="No sales available yet"
        />
      </div>

      {/* GRAPH SECTION */}
    {/* GRAPH SECTION */}
<div className="cosales-bottom">
  <div className="cosales-graph-card">
    <h3 className="graph-title">Monthly Sales Revenue</h3>

    {monthlySales.length > 0 ? (
      <div className="cosales-chart-wrap">
        <Line
          data={lineData}
          options={lineOptions}
        />
      </div>
    ) : (
      <div className="graph-placeholder">
        No sales data yet
      </div>
    )}
  </div>
</div>
    </div>
  );
}