import { useState, useEffect } from "react";
import "./co-inventory.css";
import Table from "../../../components/Table";
import { supabase } from "../../../supabase";
import { Layers, AlertTriangle, PackageX, Download } from "lucide-react";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

// ==========================================
// EXPORT PDF FUNCTION (Inventory Template)
// ==========================================
export const exportInventoryToPDF = (inventoryData, filename = "inventory-report.pdf", generatedBy = "Co-Associate") => {
  const doc = new jsPDF();

  const primaryColor = [30, 41, 59];
  const accentColor = [79, 70, 229];
  const lightBg = [248, 250, 252];

  // Header Design
  doc.setFillColor(...accentColor);
  doc.rect(14, 15, 3, 14, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.setTextColor(...primaryColor);
  doc.text("ADRENALINE AQUA WATER REFILLING STATION", 21, 22);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text("Inventory & Stock Level Report", 21, 28);

  doc.setFontSize(9);
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, 196, 22, { align: "right" });

  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.4);
  doc.line(14, 34, 196, 34);

  // Summary Box inside PDF
  const totalValueSum = inventoryData.reduce((sum, item) => sum + (Number(item.price || 0) * Number(item.quantity_available || 0)), 0);

  doc.setFillColor(...lightBg);
  doc.roundedRect(14, 40, 182, 14, 1.5, 1.5, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(...primaryColor);
  doc.text(`Total Items: ${inventoryData.length}`, 18, 49);
  doc.text(`Total Value: ₱${totalValueSum.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`, 110, 49);

  // Table Setup
  const tableColumn = ["Code", "Item Name", "Category", "Price", "In Stock", "Status"];
  const tableRows = inventoryData.map((item) => {
    let statusText = "In Stock";
    if (item.quantity_available <= 0) statusText = "Out of Stock";
    else if (item.quantity_available <= item.reorder_level) statusText = "Low Stock";

    return [
      item.inventory_code || "—",
      item.item_name || "—",
      item.category || "—",
      `₱${Number(item.price || 0).toFixed(2)}`,
      `${item.quantity_available ?? 0} pcs`,
      statusText,
    ];
  });

  autoTable(doc, {
    head: [tableColumn],
    body: tableRows,
    startY: 60,
    theme: "striped",
    headStyles: {
      fillColor: primaryColor,
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 8,
      cellPadding: 6,
    },
    bodyStyles: {
      textColor: [51, 65, 85],
      fontSize: 8,
      cellPadding: 6,
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
    margin: { left: 14, right: 14 },
    didDrawPage: (data) => {
      const pageHeight = doc.internal.pageSize.height;
      doc.setFontSize(8);
      doc.setTextColor(148, 163, 184);
      doc.text(`Generated by: ${generatedBy}`, data.settings.margin.left, pageHeight - 10);
      doc.text(`Page ${doc.internal.getNumberOfPages()}`, doc.internal.pageSize.width - data.settings.margin.right, pageHeight - 10, { align: "right" });
    },
  });

  doc.save(filename);
};

function CoInventory() {
  const [items, setItems] = useState([]);
  const [search, setSearch] = useState("");
  const [categoryFilter, setCategoryFilter] = useState("All");

  useEffect(() => {
    fetchInventory();
  }, []);

  // FETCH DATA MULA SA DATABASE
  const fetchInventory = async () => {
    const { data, error } = await supabase
      .from("inventory")
      .select("*")
      .order("item_name", { ascending: true });

    if (error) {
      console.error("Error fetching inventory:", error.message);
      return;
    }
    setItems(data || []);
  };

  // LOGIC PARA SA STATUS PILL
  const getStatus = (quantity, reorderLevel) => {
    if (quantity <= 0) return { label: "Out of Stock", class: "out" };
    if (quantity <= reorderLevel) return { label: "Low Stock", class: "low" };
    return { label: "In Stock", class: "in" };
  };

  // CALCULATIONS
  const totalInventoryValue = items.reduce((sum, item) => sum + (Number(item.price || 0) * Number(item.quantity_available || 0)), 0);
  const lowStockAlertsCount = items.filter(i => i.quantity_available > 0 && i.quantity_available <= i.reorder_level).length;
  const outOfStockAlertsCount = items.filter(i => i.quantity_available <= 0).length;

  // FILTER LOGIC
  const filteredItems = items.filter((item) => {
    const matchSearch =
      item.item_name?.toLowerCase().includes(search.toLowerCase()) ||
      item.inventory_code?.toLowerCase().includes(search.toLowerCase());
    const matchCategory = categoryFilter === "All" || item.category === categoryFilter;
    return matchSearch && matchCategory;
  });

  // EXPORT PDF HANDLER
  const handleExportPDF = () => {
    const savedUser = JSON.parse(localStorage.getItem("user")) || {};
    const userPosition = savedUser.position || savedUser.role || "Co-Associate";
    const userName = savedUser.name || savedUser.fullName || "Co-Associate";
    const generatedByFull = `${userPosition} - ${userName}`;

    exportInventoryToPDF(filteredItems, "inventory-report.pdf", generatedByFull);
  };

  // COLUMNS (READ ONLY)
  const columns = [
    { key: "inventory_code", label: "Item ID" },
    { key: "item_name", label: "Item Name" },
    { key: "category", label: "Category" },
    { key: "price", label: "Price", render: (row) => `₱${Number(row.price || 0).toFixed(2)}` },
    { key: "quantity_available", label: "Quantity" },
    {
      key: "status",
      label: "Status",
      render: (row) => {
        const status = getStatus(row.quantity_available, row.reorder_level);
        return <span className={`status-pill ${status.class}`}>{status.label}</span>;
      },
    },
    { key: "last_updated", label: "Last Updated", render: (row) => row.last_updated ? new Date(row.last_updated).toLocaleDateString() : "N/A" },
  ];

  return (
    <div className="coinventory-page">
      {/* HEADER */}
      <div className="coinventory-header">
        <h1> Co- Associate Inventory</h1>
        <p>Manage stock, availability, and product tracking</p>
      </div>

      {/* DASHBOARD SUMMARY CARDS */}
      <div className="inventory-summary-cards">
        <div className="summary-card total-val">
          <Layers className="card-icon" />
          <div>
            <h3>Total Value</h3>
            <h2>₱{totalInventoryValue.toLocaleString(undefined, { minimumFractionDigits: 2 })}</h2>
          </div>
        </div>
        <div className={`summary-card low-alert ${lowStockAlertsCount > 0 ? "active" : ""}`}>
          <AlertTriangle className="card-icon" />
          <div>
            <h3>Low Stock</h3>
            <h2>{lowStockAlertsCount}</h2>
          </div>
        </div>
        <div className={`summary-card out-alert ${outOfStockAlertsCount > 0 ? "active" : ""}`}>
          <PackageX className="card-icon" />
          <div>
            <h3>Out of Stock</h3>
            <h2>{outOfStockAlertsCount}</h2>
          </div>
        </div>
      </div>

      {/* CONTROLS */}
      <div className="cocontrols-row">
        <input
          type="text"
          className="cosearch-input"
          placeholder="Search item..."
          value={search}
          onChange={(e) => setSearch(e.target.value)}
        />
        <select
          className="cofilter-select"
          value={categoryFilter}
          onChange={(e) => setCategoryFilter(e.target.value)}
        >
          <option value="All">All Category</option>
          <option value="Water">Water</option>
          <option value="Bottle">Bottle</option>
          <option value="Equipment">Equipment</option>
        </select>

        <button className="export-pdf-btn" onClick={handleExportPDF}>
          <Download size={16} /> Export PDF
        </button>
      </div>

      {/* TABLE */}
      <div className="cotable-container">
        <Table
          columns={columns}
          data={filteredItems}
          emptyMessage="No inventory items found."
        />
      </div>
    </div>
  );
}

export default CoInventory;
