import { useState, useEffect, useRef } from "react";
import "./staff-inventory.css";
import Table from "../../../components/Table";
import { supabase } from "../../../supabase";
import {
  Plus,
  Pencil,
  Trash2,
  AlertTriangle,
  PackageX,
  Layers,
  X,
  Download,
  CheckCircle,
  XCircle,
} from "lucide-react";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

// ==========================================
// EXPORT PDF FUNCTION (Inventory Template)
// ==========================================
export const exportInventoryToPDF = (inventoryData, filename = "inventory-report.pdf", generatedBy = "System Admin") => {
  const doc = new jsPDF();

  const primaryColor = [30, 41, 59];
  const accentColor = [79, 70, 229];
  const lightBg = [248, 250, 252];

  // Header Design
  doc.setFillColor(...accentColor);
  doc.rect(14, 15, 3, 14, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.setTextColor(...primaryColor);
  doc.text("ADRENALINE AQUA WATER REFILLING STATION", 21, 22);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text("Inventory & Stock Level Report", 21, 28);

  doc.setFontSize(9);
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, 196, 22, { align: "right" });

  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.4);
  doc.line(14, 34, 196, 34);

  // Summary Box inside PDF
  const totalValueSum = inventoryData.reduce((sum, item) => sum + (Number(item.price || 0) * Number(item.quantity_available || 0)), 0);

  doc.setFillColor(...lightBg);
  doc.roundedRect(14, 40, 182, 14, 1.5, 1.5, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(...primaryColor);
  doc.text(`Total Items: ${inventoryData.length}`, 18, 49);
  doc.text(`Total Value: ₱${totalValueSum.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`, 110, 49);

  // Table Setup
  const tableColumn = ["Code", "Item Name", "Category", "Price", "In Stock", "Status"];
  const tableRows = inventoryData.map((item) => {
    let statusText = "In Stock";
    if (item.quantity_available <= 0) statusText = "Out of Stock";
    else if (item.quantity_available <= item.reorder_level) statusText = "Low Stock";

    return [
      item.inventory_code || "—",
      item.item_name || "—",
      item.category || "—",
      `₱${Number(item.price || 0).toFixed(2)}`,
      `${item.quantity_available ?? 0} pcs`,
      statusText,
    ];
  });

  autoTable(doc, {
    head: [tableColumn],
    body: tableRows,
    startY: 60,
    theme: "striped",
    headStyles: {
      fillColor: primaryColor,
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 8,
      cellPadding: 6,
    },
    bodyStyles: {
      textColor: [51, 65, 85],
      fontSize: 8,
      cellPadding: 6,
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
    margin: { left: 14, right: 14 },
    didDrawPage: (data) => {
      const pageHeight = doc.internal.pageSize.height;
      doc.setFontSize(8);
      doc.setTextColor(148, 163, 184);
      doc.text(`Generated by: ${generatedBy}`, data.settings.margin.left, pageHeight - 10);
      doc.text(`Page ${doc.internal.getNumberOfPages()}`, doc.internal.pageSize.width - data.settings.margin.right, pageHeight - 10, { align: "right" });
    },
  });

  doc.save(filename);
};

function StaffInventory() {
  const [items, setItems] = useState([]);
  const [search, setSearch] = useState("");
  const [categoryFilter, setCategoryFilter] = useState("All");
  const [sortField, setSortField] = useState("item_name");
  const [sortOrder, setSortOrder] = useState("asc");
  const [selectedItems, setSelectedItems] = useState([]);

  // MODALS CONTROL STATES
  const [showAdd, setShowAdd] = useState(false);
  const [showEdit, setShowEdit] = useState(false);
  const [showRestock, setShowRestock] = useState(false);
  const [showDeleteModal, setShowDeleteModal] = useState(false);
  const [deleteMode, setDeleteMode] = useState("single");
  const [selectedItem, setSelectedItem] = useState(null);

  // FORM INITIAL STATES
  const [formData, setFormData] = useState({
    item_name: "",
    category: "Water",
    price: "",
    quantity: "",
    reorder_level: 10,
  });
  const [restockQty, setRestockQty] = useState("");

  // ===============================
  // TOAST
  // ===============================
  const [toast, setToast] = useState({
    message: "",
    type: "success",
    show: false,
  });
  const toastTimer = useRef(null);

  const showToast = (message, type = "success") => {
    clearTimeout(toastTimer.current);
    setToast({ message, type, show: true });
    toastTimer.current = setTimeout(() => {
      setToast({ message: "", type: "success", show: false });
    }, 3000);
  };

  useEffect(() => {
    return () => clearTimeout(toastTimer.current);
  }, []);

  useEffect(() => {
    fetchInventory();
  }, []);

  // FETCH DATA FROM SUPABASE
  const fetchInventory = async () => {
    const { data, error } = await supabase
      .from("inventory")
      .select("*")
      .order("item_name", { ascending: true });

    if (error) {
      console.error("Error fetching inventory:", error.message);
      return;
    }
    setItems(data || []);
  };

  // AUTOMATED INVENTORY CODE GENERATOR
  const generateItemCode = async () => {
    const year = new Date().getFullYear();
    const { data } = await supabase
      .from("inventory")
      .select("inventory_code")
      .like("inventory_code", `INV${year}%`)
      .order("inventory_code", { ascending: false })
      .limit(1);

    let next = 1;
    if (data?.length > 0) {
      const last = data[0].inventory_code;
      next = Number(last.replace(`INV${year}`, "")) + 1;
    }
    return `INV${year}${String(next).padStart(3, "0")}`;
  };

  // INSERT: ADD NEW PRODUCT
  const handleAddProduct = async () => {
    if (!formData.item_name || !formData.price || formData.quantity === "") {
      showToast("Please fill in all required fields.", "error");
      return;
    }

    const itemCode = await generateItemCode();

    const { error } = await supabase.from("inventory").insert([
      {
        inventory_code: itemCode,
        item_name: formData.item_name,
        category: formData.category,
        price: Number(formData.price),
        quantity_available: Number(formData.quantity),
        reorder_level: Number(formData.reorder_level),
        last_updated: new Date().toISOString(),
      },
    ]);

    if (error) {
      showToast("Error adding product: " + error.message, "error");
    } else {
      showToast("Product added successfully!", "success");
      setShowAdd(false);
      resetForm();
      fetchInventory();
    }
  };

  // UPDATE: EDIT ITEM DETAILS
  const handleEditProduct = async () => {
    if (!formData.item_name || !formData.price) {
      showToast("Please fill in all required fields.", "error");
      return;
    }

    const { error } = await supabase
      .from("inventory")
      .update({
        item_name: formData.item_name,
        category: formData.category,
        price: Number(formData.price),
        reorder_level: Number(formData.reorder_level),
        last_updated: new Date().toISOString(),
      })
      .eq("inventory_code", selectedItem.inventory_code);

    if (error) {
      showToast("Update failed: " + error.message, "error");
    } else {
      showToast("Product updated successfully!", "success");
      setShowEdit(false);
      fetchInventory();
    }
  };

  // UPDATE: STOCK IN / RESTOCK
  const handleRestock = async () => {
    if (!restockQty || Number(restockQty) <= 0) {
      showToast("Enter a valid quantity.", "error");
      return;
    }

    const newQty = Number(selectedItem.quantity_available) + Number(restockQty);

    const { error } = await supabase
      .from("inventory")
      .update({
        quantity_available: newQty,
        last_updated: new Date().toISOString(),
      })
      .eq("inventory_code", selectedItem.inventory_code);

    if (error) {
      showToast("Restock failed: " + error.message, "error");
    } else {
      showToast("Stock updated successfully!", "success");
      setShowRestock(false);
      setRestockQty("");
      fetchInventory();
    }
  };

  // BUKSAN ANG DELETE MODAL (Single Item)
  const openSingleDeleteModal = (item) => {
    setSelectedItem(item);
    setDeleteMode("single");
    setShowDeleteModal(true);
  };

  // BUKSAN ANG DELETE MODAL (Bulk Items)
  const openBulkDeleteModal = () => {
    setDeleteMode("bulk");
    setShowDeleteModal(true);
  };

  // PROCEED TO DATABASE DELETION
  const handleConfirmDelete = async () => {
    if (deleteMode === "single") {
      const { error } = await supabase
        .from("inventory")
        .delete()
        .eq("inventory_code", selectedItem.inventory_code);

      if (error) {
        showToast("Delete failed: " + error.message, "error");
      } else {
        showToast("Product deleted successfully!", "success");
        setShowDeleteModal(false);
        fetchInventory();
      }
    } else if (deleteMode === "bulk") {
      const count = selectedItems.length;

      const { error } = await supabase
        .from("inventory")
        .delete()
        .in("inventory_code", selectedItems);

      if (error) {
        showToast("Delete failed: " + error.message, "error");
      } else {
        showToast(
          `${count} product${count > 1 ? "s" : ""} deleted successfully!`,
          "success"
        );
        setSelectedItems([]);
        setShowDeleteModal(false);
        fetchInventory();
      }
    }
  };

  const resetForm = () => {
    setFormData({
      item_name: "",
      category: "Water",
      price: "",
      quantity: "",
      reorder_level: 10,
    });
  };

  // DYNAMIC STATUS INDICATOR LOGIC
  const getStatus = (quantity, reorderLevel) => {
    if (quantity <= 0) return { label: "Out of Stock", class: "out" };
    if (quantity <= reorderLevel) return { label: "Low Stock", class: "low" };
    return { label: "In Stock", class: "in" };
  };

  // METRICS CALCULATIONS
  const totalInventoryValue = items.reduce((sum, item) => sum + (Number(item.price || 0) * Number(item.quantity_available || 0)), 0);
  const lowStockAlertsCount = items.filter(i => i.quantity_available > 0 && i.quantity_available <= i.reorder_level).length;
  const outOfStockAlertsCount = items.filter(i => i.quantity_available <= 0).length;

  // FILTER & SEARCH FILTERING
  const filteredItems = items.filter((item) => {
    const matchSearch =
      item.item_name?.toLowerCase().includes(search.toLowerCase()) ||
      item.inventory_code?.toLowerCase().includes(search.toLowerCase());
    const matchCategory = categoryFilter === "All" || item.category === categoryFilter;
    return matchSearch && matchCategory;
  });

  // CHECKBOX SELECTION LOGIC
  const handleSelectAll = (e) => {
    if (e.target.checked) {
      setSelectedItems(filteredItems.map((i) => i.inventory_code));
    } else {
      setSelectedItems([]);
    }
  };

  const handleSelectItem = (itemId) => {
    setSelectedItems((prev) =>
      prev.includes(itemId) ? prev.filter((id) => id !== itemId) : [...prev, itemId]
    );
  };

  // TABLE COLUMNS CONFIGURATION
  const columns = [
    {
      key: "select",
      label: (
        <input
          type="checkbox"
          onChange={handleSelectAll}
          checked={selectedItems.length === filteredItems.length && filteredItems.length > 0}
        />
      ),
      render: (row) => (
        <input
          type="checkbox"
          checked={selectedItems.includes(row.inventory_code)}
          onChange={() => handleSelectItem(row.inventory_code)}
        />
      ),
    },
    { key: "inventory_code", label: "Inventory Code" },
    { key: "item_name", label: "Item Name" },
    { key: "category", label: "Category" },
    { key: "price", label: "Price", render: (row) => `₱${Number(row.price || 0).toFixed(2)}` },
    { key: "quantity_available", label: "In Stock" },
    {
      key: "status",
      label: "Status",
      render: (row) => {
        const status = getStatus(row.quantity_available, row.reorder_level);
        return <span className={`staffstatus-pill ${status.class}`}>{status.label}</span>;
      },
    },
    {
      key: "last_updated",
      label: "Last Updated",
      render: (row) => row.last_updated ? new Date(row.last_updated).toLocaleDateString() : "N/A"
    },
    {
      key: "actions",
      label: "Action",
      render: (row) => (
        <div className="staffaction-buttons">
          <button
            className="staffrestock-icon-btn"
            title="Stock In"
            onClick={() => { setSelectedItem(row); setRestockQty(""); setShowRestock(true); }}
          >
            <Plus size={16} />
          </button>

          <button className="staffedit-icon-btn" onClick={() => {
            setSelectedItem(row);
            setFormData({ item_name: row.item_name, category: row.category, price: row.price, quantity: row.quantity_available, reorder_level: row.reorder_level });
            setShowEdit(true);
          }}><Pencil size={16} /></button>

          <button className="staffdelete-icon-btn" onClick={() => openSingleDeleteModal(row)}><Trash2 size={16} /></button>
        </div>
      ),
    },
  ];

  const restockPreview =
    Number(selectedItem?.quantity_available || 0) + Number(restockQty || 0);

  return (
    <div className="staffinventory-page">
      {/* TOAST */}
      {toast.show && (
        <div className={`staffinv-toast ${toast.type}`}>
          <div className="staffinv-toast-icon">
            {toast.type === "success" ? (
              <CheckCircle size={20} />
            ) : (
              <XCircle size={20} />
            )}
          </div>
          <div className="staffinv-toast-text">{toast.message}</div>
        </div>
      )}

      {/* TITLE HEADER */}
      <div className="staffinventory-header">
        <div>
          <h1>Inventory</h1>
          <p>Real-time stock management and automated tracking</p>
        </div>
      </div>

      {/* DASHBOARD STATUS CARDS */}
      <div className="staffinventory-summary-cards">
        <div className="staffsummary-card stafftotal-val">
          <Layers className="card-icon" />
          <div>
            <h3>Total Value</h3>
            <h2>₱{totalInventoryValue.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</h2>
          </div>
        </div>
        <div className={`staffsummary-card stafflow-alert ${lowStockAlertsCount > 0 ? "active" : ""}`}>
          <AlertTriangle className="card-icon" />
          <div>
            <h3>Low Stock Items</h3>
            <h2>{lowStockAlertsCount}</h2>
          </div>
        </div>
        <div className={`staffsummary-card staffout-alert ${outOfStockAlertsCount > 0 ? "active" : ""}`}>
          <PackageX className="card-icon" />
          <div>
            <h3>Out of Stock</h3>
            <h2>{outOfStockAlertsCount}</h2>
          </div>
        </div>
      </div>

      {/* SEARCH, FILTERS & ACTION ACTIONS */}
      <div className="staffcontrols-row">
        <div className="staffleft-controls">
          <input
            type="text"
            className="staffsearch-input"
            placeholder="Search code or name..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
          />

          <select className="stafffilter-select" value={categoryFilter} onChange={(e) => setCategoryFilter(e.target.value)}>
            <option value="All">All Categories</option>
            <option value="Water">Water</option>
            <option value="Bottle">Bottle</option>
            <option value="Equipment">Equipment</option>
          </select>
        </div>

        <div className="staffright-controls" style={{ display: "flex", gap: "10px", alignItems: "center" }}>
          {selectedItems.length > 0 && (
            <button className="staffbulk-delete-btn" onClick={openBulkDeleteModal}>
              <Trash2 size={16} /> Delete Selected ({selectedItems.length})
            </button>
          )}

          <button className="staffadd-btn" onClick={() => { resetForm(); setShowAdd(true); }}>
            <Plus size={16} /> Add Product
          </button>

          <button
            onClick={() => {
              const savedUser = JSON.parse(localStorage.getItem("user")) || {};
              const userPosition = savedUser.position || savedUser.role || "Admin";
              const userName = savedUser.name || savedUser.fullName || "System Admin";
              const generatedByFull = `${userPosition} - ${userName}`;

              exportInventoryToPDF(filteredItems, "inventory-report.pdf", generatedByFull);
            }}
            className="export-pdf-btn"
            style={{ display: "flex", alignItems: "center", gap: "6px", padding: "8px 12px", cursor: "pointer", background: "#334155", color: "#fff", border: "none", borderRadius: "6px" }}
          >
            <Download size={16} /> Export PDF
          </button>
        </div>
      </div>

      {/* RENDER DYNAMIC TABLE */}
      <div className="stafftable-container staffinventory-table">
        <Table columns={columns} data={filteredItems} />
      </div>

      {/* ========================================== */}
      {/* MODAL: ADD NEW PRODUCT                     */}
      {/* ========================================== */}
      {showAdd && (
        <div className="staffinv-modal-overlay" onClick={() => setShowAdd(false)}>
          <div className="staffinv-modal" onClick={(e) => e.stopPropagation()}>
            <div className="staffinv-modal-header">
              <div className="staffinv-modal-icon primary">
                <Plus size={22} />
              </div>
              <div className="staffinv-modal-titles">
                <h2>Add New Product</h2>
                <p>Fill in the details to add an item to inventory.</p>
              </div>
              <button className="staffinv-modal-close" onClick={() => setShowAdd(false)}>
                <X size={18} />
              </button>
            </div>

            <div className="staffinv-modal-body">
              <div className="staffinv-field">
                <label>Product Name</label>
                <input
                  type="text"
                  placeholder="e.g. 500ml"
                  value={formData.item_name}
                  onChange={(e) => setFormData({ ...formData, item_name: e.target.value })}
                />
              </div>

              <div className="staffinv-field">
                <label>Category</label>
                <select
                  value={formData.category}
                  onChange={(e) => setFormData({ ...formData, category: e.target.value })}
                >
                  <option value="Water">Water</option>
                  <option value="Bottle">Bottle</option>
                  <option value="Equipment">Equipment</option>
                </select>
              </div>

              <div className="staffinv-field-row">
                <div className="staffinv-field">
                  <label>Price (₱)</label>
                  <input
                    type="number"
                    placeholder="0.00"
                    value={formData.price}
                    onChange={(e) => setFormData({ ...formData, price: e.target.value })}
                  />
                </div>
                <div className="staffinv-field">
                  <label>Initial Stock</label>
                  <input
                    type="number"
                    placeholder="0"
                    value={formData.quantity}
                    onChange={(e) => setFormData({ ...formData, quantity: e.target.value })}
                  />
                </div>
              </div>

              <div className="staffinv-field">
                <label>Reorder Level Alert Threshold</label>
                <input
                  type="number"
                  value={formData.reorder_level}
                  onChange={(e) => setFormData({ ...formData, reorder_level: e.target.value })}
                />
                <span className="staffinv-hint">You'll see a low stock warning at or below this number.</span>
              </div>
            </div>

            <div className="staffinv-modal-footer">
              <button className="staffinv-btn ghost" onClick={() => setShowAdd(false)}>Cancel</button>
              <button className="staffinv-btn primary" onClick={handleAddProduct}>Save Product</button>
            </div>
          </div>
        </div>
      )}

      {/* ========================================== */}
      {/* MODAL: EDIT PRODUCT DETAILS                */}
      {/* ========================================== */}
      {showEdit && (
        <div className="staffinv-modal-overlay" onClick={() => setShowEdit(false)}>
          <div className="staffinv-modal" onClick={(e) => e.stopPropagation()}>
            <div className="staffinv-modal-header">
              <div className="staffinv-modal-icon primary">
                <Pencil size={20} />
              </div>
              <div className="staffinv-modal-titles">
                <h2>Edit Product Details</h2>
                <p>Editing code: <b>{selectedItem?.inventory_code}</b></p>
              </div>
              <button className="staffinv-modal-close" onClick={() => setShowEdit(false)}>
                <X size={18} />
              </button>
            </div>

            <div className="staffinv-modal-body">
              <div className="staffinv-field">
                <label>Product Name</label>
                <input
                  type="text"
                  value={formData.item_name}
                  onChange={(e) => setFormData({ ...formData, item_name: e.target.value })}
                />
              </div>

              <div className="staffinv-field">
                <label>Category</label>
                <select
                  value={formData.category}
                  onChange={(e) => setFormData({ ...formData, category: e.target.value })}
                >
                  <option value="Water">Water</option>
                  <option value="Bottle">Bottle</option>
                  <option value="Equipment">Equipment</option>
                </select>
              </div>

              <div className="staffinv-field-row">
                <div className="staffinv-field">
                  <label>Price (₱)</label>
                  <input
                    type="number"
                    value={formData.price}
                    onChange={(e) => setFormData({ ...formData, price: e.target.value })}
                  />
                </div>
                <div className="staffinv-field">
                  <label>Alert Threshold Level</label>
                  <input
                    type="number"
                    value={formData.reorder_level}
                    onChange={(e) => setFormData({ ...formData, reorder_level: e.target.value })}
                  />
                </div>
              </div>
            </div>

            <div className="staffinv-modal-footer">
              <button className="staffinv-btn ghost" onClick={() => setShowEdit(false)}>Cancel</button>
              <button className="staffinv-btn primary" onClick={handleEditProduct}>Update Changes</button>
            </div>
          </div>
        </div>
      )}

      {/* ========================================== */}
      {/* MODAL: STOCK IN ACTION                     */}
      {/* ========================================== */}
      {showRestock && (
        <div className="staffinv-modal-overlay" onClick={() => setShowRestock(false)}>
          <div className="staffinv-modal sm" onClick={(e) => e.stopPropagation()}>
            <div className="staffinv-modal-header">
              <div className="staffinv-modal-icon success">
                <Plus size={22} />
              </div>
              <div className="staffinv-modal-titles">
                <h2>Stock In</h2>
                <p>{selectedItem?.item_name}</p>
              </div>
              <button className="staffinv-modal-close" onClick={() => setShowRestock(false)}>
                <X size={18} />
              </button>
            </div>

            <div className="staffinv-modal-body">
              <div className="staffinv-stock-card">
                <div>
                  <span>Current</span>
                  <b>{selectedItem?.quantity_available} pcs</b>
                </div>
                <div className="staffinv-stock-arrow">→</div>
                <div>
                  <span>After restock</span>
                  <b className="after">{restockPreview} pcs</b>
                </div>
              </div>

              <div className="staffinv-field">
                <label>Quantity to Add</label>
                <input
                  type="number"
                  placeholder="Enter amount to add"
                  value={restockQty}
                  onChange={(e) => setRestockQty(e.target.value)}
                />
              </div>
            </div>

            <div className="staffinv-modal-footer">
              <button className="staffinv-btn ghost" onClick={() => setShowRestock(false)}>Cancel</button>
              <button className="staffinv-btn success" onClick={handleRestock}>Increase Inventory</button>
            </div>
          </div>
        </div>
      )}

      {/* ========================================== */}
      {/* MODAL: CONFIRM DELETE                      */}
      {/* ========================================== */}
      {showDeleteModal && (
        <div className="staffinv-modal-overlay" onClick={() => setShowDeleteModal(false)}>
          <div className="staffinv-modal sm" onClick={(e) => e.stopPropagation()}>
            <div className="staffinv-delete-body">
              <div className="staffinv-delete-icon">
                <AlertTriangle size={28} />
              </div>
              <h2>Confirm Deletion</h2>
              <p className="staffinv-delete-text">
                {deleteMode === "single"
                  ? "Are you sure you want to delete this product? This will permanently remove the inventory record and cannot be undone."
                  : "Are you sure you want to delete these products? This will permanently remove the selected inventory records and cannot be undone."}
              </p>

              <div className="staffinv-details-box">
                {deleteMode === "single" ? (
                  <>
                    <div className="staffinv-detail-row"><span>Inventory Code</span><b>{selectedItem?.inventory_code}</b></div>
                    <div className="staffinv-detail-row"><span>Product Name</span><b>{selectedItem?.item_name}</b></div>
                    <div className="staffinv-detail-row"><span>Category</span><b>{selectedItem?.category}</b></div>
                    <div className="staffinv-detail-row"><span>In Stock</span><b>{selectedItem?.quantity_available} pcs</b></div>
                    <div className="staffinv-detail-row"><span>Price</span><b>₱{Number(selectedItem?.price || 0).toFixed(2)}</b></div>
                  </>
                ) : (
                  <>
                    <div className="staffinv-detail-row"><span>Items Selected</span><b>{selectedItems.length}</b></div>
                    <div className="staffinv-code-list">
                      {selectedItems.map((code) => (
                        <span key={code} className="staffinv-code-chip">{code}</span>
                      ))}
                    </div>
                  </>
                )}
              </div>
            </div>

            <div className="staffinv-modal-footer split">
              <button className="staffinv-btn ghost" onClick={() => setShowDeleteModal(false)}>
                No, Cancel
              </button>
              <button className="staffinv-btn danger" onClick={handleConfirmDelete}>
                {deleteMode === "single" ? "Delete Product" : `Delete Selected (${selectedItems.length})`}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

export default StaffInventory;
