import { useState, useEffect } from "react";
import "./co-expenses.css";
import Table from "../../../components/Table";
import { supabase } from "../../../supabase";
import { Calendar, DollarSign, Layers, Download } from "lucide-react";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

// ==========================================
// EXPORT PDF FUNCTION (kapareho ng design ng Admin Expenses)
// ==========================================
// PHP ang gamit imbes na ₱ dahil hindi suportado ng default font ng jsPDF ang ₱
const pesoText = (n, decimals = 2) =>
  "PHP " +
  Number(n || 0).toLocaleString("en-US", {
    minimumFractionDigits: decimals,
    maximumFractionDigits: decimals,
  });

export const exportExpensesToPDF = (
  expensesData,
  filename = "expenses-report.pdf",
  generatedBy = "Co-Associate"
) => {
  const doc = new jsPDF();

  const primaryColor = [30, 41, 59];
  const accentColor = [79, 70, 229];
  const lightBg = [248, 250, 252];

  // Header Design
  doc.setFillColor(...accentColor);
  doc.rect(14, 15, 3, 14, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.setTextColor(...primaryColor);
  doc.text("ADRENALINE AQUA WATER REFILLING STATION", 21, 22);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text("Expenses & Cash Outflow Report", 21, 28);

  doc.setFontSize(9);
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, 196, 22, { align: "right" });

  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.4);
  doc.line(14, 34, 196, 34);

  // Summary Box inside PDF
  const totalAmountSum = expensesData.reduce(
    (sum, item) => sum + Number(item.amount || 0),
    0
  );

  doc.setFillColor(...lightBg);
  doc.roundedRect(14, 40, 182, 14, 1.5, 1.5, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(...primaryColor);
  doc.text(`Total Records: ${expensesData.length}`, 18, 49);
  doc.text(`Total Outflow: ${pesoText(totalAmountSum)}`, 110, 49);

  // Table Setup
  const tableColumn = ["Expense ID", "Date", "Category", "Description", "Amount"];
  const tableRows = expensesData.map((exp) => [
    exp.expenses_code || "-",
    exp.date ? new Date(exp.date).toLocaleDateString() : "-",
    exp.category || "-",
    exp.description || "-",
    pesoText(exp.amount),
  ]);

  autoTable(doc, {
    head: [tableColumn],
    body: tableRows,
    startY: 60,
    theme: "striped",
    headStyles: {
      fillColor: primaryColor,
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 8,
      cellPadding: 6,
    },
    bodyStyles: {
      textColor: [51, 65, 85],
      fontSize: 8,
      cellPadding: 6,
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
    margin: { left: 14, right: 14 },
    didDrawPage: (data) => {
      const pageHeight = doc.internal.pageSize.height;
      doc.setFontSize(8);
      doc.setTextColor(148, 163, 184);
      doc.text(`Generated by: ${generatedBy}`, data.settings.margin.left, pageHeight - 10);
      doc.text(
        `Page ${doc.internal.getNumberOfPages()}`,
        doc.internal.pageSize.width - data.settings.margin.right,
        pageHeight - 10,
        { align: "right" }
      );
    },
  });

  doc.save(filename);
};

export default function CoExpenses() {
  const [expenses, setExpenses] = useState([]);
  const [search, setSearch] = useState("");
  const [categoryFilter, setCategoryFilter] = useState("All");
  const [timeFilter, setTimeFilter] = useState("All");

  useEffect(() => {
    fetchExpenses();
  }, []);

  const fetchExpenses = async () => {
    const { data, error } = await supabase
      .from("expenses")
      .select("*")
      .order("date", { ascending: false });

    if (error) {
      console.error("Error fetching expenses:", error.message);
      return;
    }
    setExpenses(data || []);
  };

  // SUMMARY CALCULATIONS
  const getSummaryTotals = () => {
    const now = new Date();
    let daily = 0, weekly = 0, monthly = 0;

    expenses.forEach((item) => {
      const expDate = new Date(item.date);
      const diffTime = Math.abs(now - expDate);
      const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));

      if (now.toDateString() === expDate.toDateString()) daily += Number(item.amount || 0);
      if (diffDays <= 7) weekly += Number(item.amount || 0);
      if (now.getMonth() === expDate.getMonth() && now.getFullYear() === expDate.getFullYear()) monthly += Number(item.amount || 0);
    });
    return { daily, weekly, monthly };
  };

  const totals = getSummaryTotals();

  // CATEGORY BREAKDOWN
  const getCategoryBreakdown = () => {
    const breakdown = { Utilities: 0, Salary: 0, Maintenance: 0, Supplies: 0 };
    let totalAll = 0;
    expenses.forEach((item) => {
      if (breakdown[item.category] !== undefined) {
        breakdown[item.category] += Number(item.amount || 0);
        totalAll += Number(item.amount || 0);
      }
    });
    return { breakdown, totalAll };
  };

  const { breakdown, totalAll } = getCategoryBreakdown();

  // FILTER & SEARCH LOGIC
  const filteredItems = expenses.filter((item) => {
    const matchSearch = item.expenses_code?.toLowerCase().includes(search.toLowerCase()) || 
                        item.description?.toLowerCase().includes(search.toLowerCase());
    const matchCategory = categoryFilter === "All" || item.category === categoryFilter;
    
    const now = new Date();
    const expDate = new Date(item.date);
    const diffDays = Math.ceil(Math.abs(now - expDate) / (1000 * 60 * 60 * 24));
    let matchTime = true;
    if (timeFilter === "Day") matchTime = now.toDateString() === expDate.toDateString();
    if (timeFilter === "Week") matchTime = diffDays <= 7;
    if (timeFilter === "Month") matchTime = now.getMonth() === expDate.getMonth() && now.getFullYear() === expDate.getFullYear();

    return matchSearch && matchCategory && matchTime;
  });

  const columns = [
    { key: "expenses_code", label: "Expense ID" },
    { key: "date", label: "Date", render: (row) => row.date ? new Date(row.date).toLocaleDateString() : "N/A" },
    { key: "category", label: "Category" },
    { key: "description", label: "Description" },
    { key: "amount", label: "Amount", render: (row) => `₱${Number(row.amount || 0).toLocaleString(undefined, {minimumFractionDigits: 2})}` }
  ];

  // EXPORT PDF
  const handleExportPDF = () => {
    if (filteredItems.length === 0) return;

    let generatedByFull = "Co-Associate";
    try {
      const savedUser = JSON.parse(localStorage.getItem("user")) || {};
      const userPosition = savedUser.position || savedUser.role || "Co-Associate";
      const userName = savedUser.name || savedUser.fullName;
      generatedByFull = userName ? `${userPosition} - ${userName}` : userPosition;
    } catch (err) {
      console.error("Could not read user:", err);
    }

    exportExpensesToPDF(
      filteredItems,
      `expenses-report-${new Date().toISOString().split("T")[0]}.pdf`,
      generatedByFull
    );
  };

  const fmt = (n) =>
    Number(n || 0).toLocaleString(undefined, {
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
    });

  return (
    <div className="coexpenses-page">
      <div className="coexpenses-header">
        <h1>Expenses</h1>
        <p>Real-time cash outflow tracking and category cost analysis</p>
      </div>

      <div className="inventory-summary-cards">
        <div className="summary-card">
          <div className="card-icon-box"><Calendar className="card-icon" /></div>
          <div>
            <h3>Today's Outflow</h3>
            <h2>₱{fmt(totals.daily)}</h2>
          </div>
        </div>

        <div className="summary-card">
          <div className="card-icon-box"><DollarSign className="card-icon" /></div>
          <div>
            <h3>This Week</h3>
            <h2>₱{fmt(totals.weekly)}</h2>
          </div>
        </div>

        <div className="summary-card">
          <div className="card-icon-box"><Layers className="card-icon" /></div>
          <div>
            <h3>This Month</h3>
            <h2>₱{fmt(totals.monthly)}</h2>
          </div>
        </div>
      </div>

      <div className="coexpenses-controls">
        <select
          className="coexpenses-filter"
          value={categoryFilter}
          onChange={(e) => setCategoryFilter(e.target.value)}
        >
          <option value="All">All Categories</option>
          <option value="Utilities">Utilities</option>
          <option value="Salary">Salary</option>
          <option value="Maintenance">Maintenance</option>
          <option value="Supplies">Supplies</option>
        </select>

        <input
          type="text"
          className="coexpenses-search"
          placeholder="Search code or description..."
          value={search}
          onChange={(e) => setSearch(e.target.value)}
        />

        <select
          className="coexpenses-filter"
          value={timeFilter}
          onChange={(e) => setTimeFilter(e.target.value)}
        >
          <option value="All">All Time</option>
          <option value="Day">Today</option>
          <option value="Week">This Week</option>
          <option value="Month">This Month</option>
        </select>

        <button
          type="button"
          className="coexpenses-export-btn"
          onClick={handleExportPDF}
          disabled={filteredItems.length === 0}
        >
          <Download size={18} /> Export PDF
        </button>
      </div>

      <div className="coexpenses-table-container">
        <Table columns={columns} data={filteredItems} emptyMessage="No expenses recorded" />
      </div>

      {/* BOTTOM SECTION: LOGS & CHART */}
      <div className="expenses-bottom-layout">
        {/* LEFT: Recent Expense Activity */}
        <div className="expense-analysis-box">
          <h3>Recent Expense Activity</h3>
          <div className="activity-timeline-container">
            {expenses.slice(0, 5).map((item, idx) => (
              <div className="activity-timeline-item" key={idx}>
                <span className="timeline-dot"></span>
                <div className="timeline-log-details">
                  <div className="timeline-meta">
                    <span className="timeline-code">{item.expenses_code}</span>
                    <span className="timeline-date">
                      {new Date(item.date).toLocaleDateString()}
                    </span>
                  </div>
                  <p>
                    Spent <b>₱{fmt(item.amount)}</b> on {item.description}
                  </p>
                </div>
              </div>
            ))}
            {expenses.length === 0 && <p className="timeline-empty">No recent activity</p>}
          </div>
        </div>

        {/* RIGHT: Category Summary Chart */}
        <div className="expense-analysis-box">
          <h3>Category Summary Chart</h3>
          <div className="chart-bars-wrapper">
            {Object.keys(breakdown).map((cat) => {
              const amount = breakdown[cat];
              const percentage = totalAll > 0 ? (amount / totalAll) * 100 : 0;
              return (
                <div className="chart-bar-row" key={cat}>
                  <div className="chart-label-group">
                    <span>{cat}</span>
                    <span>
                      ₱{amount.toLocaleString()} ({percentage.toFixed(0)}%)
                    </span>
                  </div>
                  <div className="progress-bar-bg">
                    <div
                      className="progress-bar-fill"
                      style={{ width: `${percentage}%` }}
                    ></div>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </div>
    </div>
  );
}
