import { useState, useEffect } from "react";
import "./staff-orders.css";
import Table from "../../../components/Table";
import { supabase } from "../../../supabase";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

import {
  Eye,
  Pencil,
  Trash2,
  X,
  CheckCircle,
  XCircle,
  Download
} from "lucide-react";

// ==========================================
// EXPORT PDF FUNCTION (Modern Style - Delivery Template)
// ==========================================
export const exportOrdersToPDF = (ordersData, filename = "orders-report.pdf", generatedBy = "System Admin") => {
  const doc = new jsPDF();

  const primaryColor = [30, 41, 59];
  const accentColor = [79, 70, 229];
  const lightBg = [248, 250, 252];

  doc.setFillColor(...accentColor);
  doc.rect(14, 15, 3, 14, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.setTextColor(...primaryColor);
  doc.text("ADRENALINE AQUA WATER REFILLING STATION", 21, 22);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text("Orders & Container Status Report", 21, 28);

  doc.setFontSize(9);
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, 196, 22, { align: "right" });

  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.4);
  doc.line(14, 34, 196, 34);

  const total = ordersData.length;
  const pending = ordersData.filter(o => o.status === 'Pending').length;
  const processing = ordersData.filter(o => o.status === 'Processing').length;
  const delivered = ordersData.filter(o => o.status === 'Delivered').length;

  doc.setFillColor(...lightBg);
  doc.roundedRect(14, 40, 182, 14, 1.5, 1.5, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(8.5);
  doc.setTextColor(...primaryColor);
  doc.text(`Total: ${total}`, 18, 49);
  doc.text(`Pending: ${pending}`, 60, 49);
  doc.text(`Processing: ${processing}`, 110, 49);
  doc.text(`Delivered: ${delivered}`, 160, 49);

  const tableColumn = [
    "Order ID",
    "Item Name",
    "Customer",
    "Qty",
    "Containers",
    "Payment",
    "Status"
  ];

  const tableRows = ordersData.map((order) => [
    order.order_code || "—",
    order.item_name || "—",
    order.full_name || "—",
    order.quantity || 0,
    order.borrowed_containers || 0,
    order.payment_method || "—",
    order.status || "—",
  ]);

  autoTable(doc, {
    head: [tableColumn],
    body: tableRows,
    startY: 60,
    theme: "striped",
    headStyles: {
      fillColor: primaryColor,
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 8,
      cellPadding: 6,
    },
    bodyStyles: {
      textColor: [51, 65, 85],
      fontSize: 8,
      cellPadding: 6,
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
    margin: { left: 14, right: 14 },
    didDrawPage: (data) => {
      const pageHeight = doc.internal.pageSize.height;
      doc.setFontSize(8);
      doc.setTextColor(148, 163, 184);

      doc.text(`Generated by: ${generatedBy}`, data.settings.margin.left, pageHeight - 10);

      doc.text(
        `Page ${doc.internal.getNumberOfPages()}`,
        doc.internal.pageSize.width - data.settings.margin.right,
        pageHeight - 10,
        { align: "right" }
      );
    },
  });

  doc.save(filename);
};

function StaffOrders() {

  const [orders, setOrders] = useState([]);
  const [search, setSearch] = useState("");
  const [statusFilter, setStatusFilter] = useState("All");
  const [selectedOrder, setSelectedOrder] = useState(null);
  const [typeFilter, setTypeFilter] = useState("All");

  const [inventoryStock, setInventoryStock] = useState([]);
  const [deliveryFee, setDeliveryFee] = useState(0);
  const [distance, setDistance] = useState(0);

  // MODALS
  const [showView, setShowView] = useState(false);
  const [showEdit, setShowEdit] = useState(false);
  const [showDelete, setShowDelete] = useState(false);
  const [showAdd, setShowAdd] = useState(false);

  // ADD DATA
  const [addData, setAddData] = useState({
    water_type: "Purified",
    size_variant: "",
    quantity: 1,
    order_type: "Delivery",
    full_name: "",
    contact_number: "",
    delivery_date: "",
    delivery_address: "",
    payment_method: "",
    borrowed_containers: 0,
    container_status: "Unreturned",
  });

  const [toast, setToast] = useState({
    message: "",
    type: "",
    show: false,
  });

  const showToast = (message, type = "success") => {
    setToast({ message, type, show: true });

    setTimeout(() => {
      setToast({ message: "", type: "", show: false });
    }, 2500);
  };

  const selectedItemObj = inventoryStock.find(
    (inv) => inv.item_name === addData.size_variant
  );

  const unitPrice = selectedItemObj ? Number(selectedItemObj.price || 0) : 0;
  const computedDeliveryFee = addData.order_type === "Delivery" ? Number(deliveryFee || 0) : 0;
  const totalAmount = (unitPrice * Number(addData.quantity || 0)) + computedDeliveryFee;

  const is500mlDeliveryInvalid =
    addData.order_type === "Delivery" &&
    addData.size_variant.toLowerCase().includes("500ml") &&
    Number(addData.quantity) < 12;

  useEffect(() => {
    let timeout;

    const compute = async () => {
      if (addData.order_type !== "Delivery") {
        setDistance(0);
        setDeliveryFee(0);
        return;
      }

      if (!addData.delivery_address || addData.delivery_address.trim().length < 5) {
        setDistance(0);
        setDeliveryFee(0);
        return;
      }

      const coords = await geocodeAddress(addData.delivery_address);

      if (!coords) {
        setDistance(0);
        setDeliveryFee(5);
        return;
      }

      const km = getDistanceKm(
        coords.lat,
        coords.lng,
        14.8294,
        120.7354
      );

      setDistance(km);

      const isHagonoy = addData.delivery_address.toLowerCase().includes("hagonoy");

      let fee = 0;
      const itemSize = addData.size_variant || "";

      if ((itemSize.includes("350ml") || itemSize.includes("500ml")) && isHagonoy) {
        fee = 0;
      } else if (!km || km <= 4) {
        fee = 5;
      } else {
        fee = 10;
      }

      setDeliveryFee(fee);
    };

    timeout = setTimeout(compute, 800);

    return () => clearTimeout(timeout);
  }, [addData.delivery_address, addData.order_type, addData.size_variant]);

  const generateSalesCode = async () => {
    const year = new Date().getFullYear();
    const { data } = await supabase
      .from("sales")
      .select("sales_code")
      .like("sales_code", `SAL${year}%`)
      .order("sales_code", { ascending: false })
      .limit(1);

    let nextNumber = 1;
    if (data?.length > 0 && data[0].sales_code) {
      const lastCode = data[0].sales_code;
      const numberPart = lastCode.replace(`SAL${year}`, "");
      nextNumber = Number(numberPart) + 1;
    }
    return `SAL${year}${String(nextNumber).padStart(3, "0")}`;
  };

  const geocodeAddress = async (address) => {
    if (!address) return null;

    try {
      const res = await fetch(
        `https://nominatim.openstreetmap.org/search?format=json&q=${encodeURIComponent(address)}`
      );

      const data = await res.json();

      if (!data || data.length === 0) return null;

      return {
        lat: parseFloat(data[0].lat),
        lng: parseFloat(data[0].lon),
      };
    } catch (err) {
      console.log("Geocode error:", err);
      return null;
    }
  };

  const getDistanceKm = (lat1, lon1, lat2, lon2) => {
    const R = 6371;

    const dLat = (lat2 - lat1) * Math.PI / 180;
    const dLon = (lon2 - lon1) * Math.PI / 180;

    const a =
      Math.sin(dLat / 2) * Math.sin(dLat / 2) +
      Math.cos(lat1 * Math.PI / 180) *
      Math.cos(lat2 * Math.PI / 180) *
      Math.sin(dLon / 2) *
      Math.sin(dLon / 2);

    const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));

    return R * c;
  };

  const generateOrderCode = async () => {
    const year = new Date().getFullYear();
    const { data } = await supabase
      .from("orders")
      .select("order_code")
      .like("order_code", `ORD${year}%`)
      .order("order_code", { ascending: false })
      .limit(1);

    let next = 1;
    if (data?.length > 0) {
      const last = data[0].order_code;
      next = Number(last.replace(`ORD${year}`, "")) + 1;
    }
    return `ORD${year}${String(next).padStart(3, "0")}`;
  };

  const generateDeliveryCode = async () => {
    const year = new Date().getFullYear();
    const { data } = await supabase
      .from("delivery_schedule")
      .select("delivery_code")
      .like("delivery_code", `DEL${year}%`)
      .order("delivery_code", { ascending: false })
      .limit(1);

    let nextNumber = 1;
    if (data?.length > 0 && data[0].delivery_code) {
      const lastCode = data[0].delivery_code;
      const numberPart = lastCode.replace(`DEL${year}`, "");
      nextNumber = Number(numberPart) + 1;
    }
    return `DEL${year}${String(nextNumber).padStart(3, "0")}`;
  };

  const [editData, setEditData] = useState({
    order_code: "",
    order_type: "",
    full_name: "",
    delivery_date: "",
    quantity: "",
    payment_method: "",
    payment_status: "",
    status: "",
    borrowed_containers: 0,
    container_status: "Unreturned",
  });

  useEffect(() => {
    fetchOrders();
    fetchInventoryStocks();
  }, []);

  const fetchInventoryStocks = async () => {
    const { data, error } = await supabase.from("inventory").select("*");
    if (!error) {
      setInventoryStock(data || []);
    }
  };

  const getItemStock = (itemName) => {
    const item = inventoryStock.find((inv) => inv.item_name === itemName);
    return item ? Number(item.quantity_available) : 0;
  };

  const fetchOrders = async () => {
    const { data, error } = await supabase
      .from("orders")
      .select(`
        *,
        order_items!order_items_order_id_fkey(
          item_name,
          quantity
        ),
        container_transactions(
          delivered_quantity,
          returned_quantity,
          outstanding_quantity,
          container_status
        )
      `)
      .order("delivery_date");

    if (error) {
      console.log(error.message);
      return;
    }

    const merged = (data || []).map((order) => {
      const container = order.container_transactions?.[0] || {};
      return {
        id: order.order_id || order.id,
        order_code: order.order_code,
        delivery_code: order.delivery_code || "-",
        order_type: order.order_type || "-",
        full_name: order.full_name,
        delivery_date: order.delivery_date,
        payment_method: order.payment_method,
        payment_status: order.payment_status,
        receipt_url: order.receipt_url,
        status: order.status,
        total_amount: order.total_amount,

        quantity: order.order_items
          ? order.order_items.reduce((sum, i) => sum + Number(i.quantity || 0), 0)
          : 0,

        item_name: order.order_items
          ? order.order_items.map(i => i.item_name).join(", ")
          : "No items",

        borrowed_containers: container.delivered_quantity || 0,
        container_status: container.container_status || "Unreturned",
        returned_quantity: container.returned_quantity || 0,
        outstanding_quantity: container.outstanding_quantity || 0,
      };
    });

    setOrders(merged);
  };

  const handleAddOrder = async () => {
    if (
      !addData.size_variant ||
      !addData.order_type ||
      !addData.full_name ||
      !addData.contact_number ||
      !addData.payment_method
    ) {
      showToast("Complete all fields.", "error");
      return;
    }

    if (addData.order_type === "Delivery") {
      if (!addData.delivery_date || !addData.delivery_address) {
        showToast("Please complete delivery details.", "error");
        return;
      }
    }

    if (is500mlDeliveryInvalid) {
      showToast("Minimum order for 500ml delivery is 12 pcs.", "error");
      return;
    }

    const targetItemName = addData.size_variant;
    const currentStock = getItemStock(targetItemName);

    if (currentStock < Number(addData.quantity)) {
      showToast(`Kulang ang stock! Available lang ay ${currentStock}.`, "error");
      return;
    }

    const orderCode = await generateOrderCode();
    let deliveryCode = null;
    if (addData.order_type === "Delivery") {
      deliveryCode = await generateDeliveryCode();
    }

    const { data: orderData, error: orderError } = await supabase
      .from("orders")
      .insert([
        {
          order_code: orderCode,
          order_date: new Date(),
          full_name: addData.full_name,
          contact_number: addData.contact_number,
          order_type: addData.order_type,
          delivery_date: addData.order_type === "Delivery" ? addData.delivery_date : null,
          delivery_address: addData.order_type === "Delivery" ? addData.delivery_address : null,
          payment_method: addData.payment_method,
          payment_status: addData.payment_status,
          status: "Pending",
          total_amount: totalAmount,
        },
      ])
      .select("order_id")
      .single();

    if (orderError) {
      console.log(orderError.message);
      showToast(orderError.message, "error");
      return;
    }

    const { error: itemError } = await supabase
      .from("order_items")
      .insert([
        {
          order_id: orderData.order_id,
          item_name: targetItemName,
          water_type: addData.water_type,
          size_variant: addData.size_variant,
          quantity: addData.quantity,
          unit_price: unitPrice,
        },
      ]);

    if (itemError) {
      console.log("Item Insert Error:", itemError.message);
    }

    if (orderData?.order_id && addData.order_type === "Delivery") {
      const borrowedQty = Number(addData.borrowed_containers || 0);
      const { error: containerError } = await supabase
        .from("container_transactions")
        .insert([
          {
            order_id: orderData.order_id,
            customer_name: addData.full_name,
            contact_number: addData.contact_number,
            delivered_quantity: borrowedQty,
            returned_quantity: 0,
            outstanding_quantity: borrowedQty,
            container_status: addData.container_status,
          }
        ]);

      if (containerError) {
        console.log("Container Transaction Error:", containerError.message);
      }
    }

    if (addData.order_type === "Delivery" && orderData?.order_id) {
      const { error: deliveryError } = await supabase
        .from("delivery_schedule")
        .insert([
          {
            order_id: orderData.order_id,
            delivery_code: deliveryCode,
            delivery_date: addData.delivery_date,
            assigned_rider: addData.assigned_rider || null,
            delivery_status: "Pending"
          }
        ]);

      if (deliveryError) {
        console.log("Delivery Schedule Error:", deliveryError.message);
      }
    }

    const { error: rpcError } = await supabase.rpc("deduct_inventory_stock", {
      p_item_name: targetItemName,
      p_qty: Number(addData.quantity)
    });

    if (rpcError) {
      console.log("RPC Deduction Error:", rpcError.message);
    }

    showToast("Order added successfully!", "success");
    setShowAdd(false);
    fetchOrders();
    fetchInventoryStocks();
  };

  const handleView = (row) => {
    setSelectedOrder(row);
    setShowView(true);
  };

  const handleEdit = (row) => {
    setSelectedOrder(row);
    setEditData({
      order_code: row.order_code || "",
      order_type: row.order_type || "Delivery",
      full_name: row.full_name || "",
      delivery_date: row.delivery_date || "",
      quantity: row.quantity || "",
      payment_method: row.payment_method || "",
      payment_status: row.payment_status || "Pending",
      status: row.status || "Pending",
      borrowed_containers: row.borrowed_containers || 0,
      container_status: row.container_status || "Unreturned",
    });
    setShowEdit(true);
  };

  const handleSaveChanges = async () => {
    try {
      const { error: updateError } = await supabase
        .from("orders")
        .update({
          order_type: editData.order_type,
          full_name: editData.full_name,
          delivery_date: editData.delivery_date,
          status: editData.status,
          payment_method: editData.payment_method,
          payment_status: editData.payment_status,
        })
        .eq("order_code", selectedOrder.order_code);

      if (updateError) {
        showToast("Failed to update order: " + updateError.message, "error");
        return;
      }

      await supabase
        .from("container_transactions")
        .update({
          delivered_quantity: Number(editData.borrowed_containers),
          outstanding_quantity: Number(editData.borrowed_containers) - Number(selectedOrder.returned_quantity || 0),
          container_status: editData.container_status,
        })
        .eq("order_id", selectedOrder.id);

      if (editData.status === "Delivered") {
        const { data: existingSales } = await supabase
          .from("sales")
          .select("sales_code")
          .eq("order_id", selectedOrder.id)
          .maybeSingle();

        if (!existingSales) {
          const salesCode = await generateSalesCode();
          const totalSalesAmount = selectedOrder.total_amount || 0;

          await supabase.from("sales").insert([
            {
              sales_code: salesCode,
              order_id: selectedOrder.id,
              total_products: Number(selectedOrder.quantity || 0),
              total_sales: totalSalesAmount,
              payment_method: editData.payment_method,
              date: new Date(),
            },
          ]);
        }
      }
      showToast("Order updated successfully!", "success");
      setShowEdit(false);
      fetchOrders();
    } catch (err) {
      console.error("System Error during save:", err);
    }
  };

  const handleDelete = (row) => {
    setSelectedOrder(row);
    setShowDelete(true);
  };

  const confirmDelete = async () => {
    const { error } = await supabase
      .from("orders")
      .delete()
      .eq("order_code", selectedOrder.order_code);

    if (error) {
      showToast("Failed to delete order", "error");
    } else {
      setShowDelete(false);
      fetchOrders();
      showToast("Order deleted successfully!", "success");
    }
  };

  // ===============================
  // UPDATE PAYMENT STATUS (Verify / Reject)
  // ===============================
  const updatePaymentStatus = async (newStatus) => {
    const { error } = await supabase
      .from("orders")
      .update({ payment_status: newStatus })
      .eq("order_code", selectedOrder.order_code);

    if (error) {
      showToast("Failed to update payment status: " + error.message, "error");
      return;
    }

    showToast(`Payment marked as ${newStatus}!`, "success");
    setSelectedOrder({ ...selectedOrder, payment_status: newStatus });
    fetchOrders();
  };

  const filteredOrders = orders.filter((order) => {
    const matchesSearch =
      order.order_code?.toLowerCase().includes(search.toLowerCase()) ||
      order.full_name?.toLowerCase().includes(search.toLowerCase());

    const matchesStatus =
      statusFilter === "All" ||
      order.status === statusFilter;

    const matchesType =
      typeFilter === "All" ||
      order.order_type === typeFilter;

    return matchesSearch && matchesStatus && matchesType;
  });

  const columns = [
    { key: "order_code", label: "Order ID" },
    {
      key: "item_name",
      label: "Item Name",
      render: (row) => <span>{row.item_name}</span>,
    },
    { key: "full_name", label: "Customer" },
    { key: "delivery_date", label: "Delivery Date" },
    {
      key: "quantity",
      label: "Qty",
      render: (row) => row.quantity,
    },
    {
      key: "borrowed_containers",
      label: "Containers Borrowed",
      render: (row) => row.borrowed_containers,
    },
    {
      key: "container_status",
      label: "Container Status",
      render: (row) => (
        <span className={`StfOrd-status ${row.container_status?.toLowerCase()}`}>
          {row.container_status}
        </span>
      ),
    },
    { key: "payment_method", label: "Payment Method" },
    {
      key: "payment_status",
      label: "Payment Status",
      render: (row) =>
        row.payment_method?.toLowerCase() === "gcash" ? (
          <span className={`StfOrd-status ${(row.payment_status || "pending").toLowerCase()}`}>
            {row.payment_status || "Pending"}
          </span>
        ) : (
          <span style={{ color: "#94a3b8" }}>N/A</span>
        ),
    },
    {
      key: "status",
      label: "Order Status",
      render: (row) => (
        <span className={`StfOrd-status ${row.status?.toLowerCase()}`}>
          {row.status}
        </span>
      ),
    },
    {
      key: "actions",
      label: "Actions",
      render: (row) => (
        <div className="StfOrd-actions">
          <button className="StfOrd-iconBtn view" onClick={() => handleView(row)}><Eye size={18} /></button>
          <button className="StfOrd-iconBtn edit" onClick={() => handleEdit(row)}><Pencil size={18} /></button>
          <button className="StfOrd-iconBtn delete" onClick={() => handleDelete(row)}><Trash2 size={18} /></button>
        </div>
      ),
    },
  ];

  return (
    <div className="StfOrd-page">

      {toast.show && (
        <div className={`toast ${toast.type} show`}>
          <div className="toast-icon">
            {toast.type === "success" ? <CheckCircle size={18} /> : <XCircle size={18} />}
          </div>
          <div className="toast-text">{toast.message}</div>
        </div>
      )}

      <div className="StfOrd-header">
        <div>
          <h1>Orders</h1>
          <p>Manage and track customer transactions and containers</p>
        </div>
      </div>

      <div className="StfOrd-controls">
        <input
          className="StfOrd-search"
          placeholder="Search orders..."
          value={search}
          onChange={(e) => setSearch(e.target.value)}
        />
        <select className="StfOrd-filter" value={typeFilter} onChange={(e) => setTypeFilter(e.target.value)}>
          <option value="All">All Orders</option>
          <option value="Delivery">Delivery</option>
          <option value="Pickup">Pickup</option>
        </select>
        <select className="StfOrd-filter" value={statusFilter} onChange={(e) => setStatusFilter(e.target.value)}>
          <option value="All">All Status</option>
          <option value="Pending">Pending</option>
          <option value="Processing">Processing</option>
          <option value="Delivered">Delivered</option>
        </select>

        <button className="StfOrd-addBtn" onClick={() => setShowAdd(true)}>+ Add Order</button>

        <button
          onClick={() => {
            const savedUser = JSON.parse(localStorage.getItem("user")) || {};
            const userPosition = savedUser.position || savedUser.role || "Admin";
            const userName = savedUser.name || savedUser.fullName || "System Admin";
            const generatedByFull = `${userPosition} - ${userName}`;

            exportOrdersToPDF(filteredOrders, "orders-report.pdf", generatedByFull);
          }}
          className="export-pdf-btn"
          style={{ display: "flex", alignItems: "center", gap: "6px", padding: "8px 12px", cursor: "pointer" }}
        >
          <Download size={18} /> Export PDF
        </button>
      </div>

      <div className="table-container">
        <Table columns={columns} data={filteredOrders} emptyMessage="No orders recorded yet." />
      </div>

      {/* VIEW MODAL */}
      {showView && (
        <div className="StfOrd-modal-overlay">
          <div className="StfOrd-view-modal">
            <button className="StfOrd-close-btn" onClick={() => setShowView(false)}><X size={20} /></button>
            <h2>Order Summary</h2>
            <div className="StfOrd-view-info">
              <div><label>Order ID</label><p>{selectedOrder?.order_code}</p></div>
              <div><label>Customer</label><p>{selectedOrder?.full_name}</p></div>
              <div><label>Delivery Date</label><p>{selectedOrder?.delivery_date}</p></div>
              <div><label>Quantity</label><p>{selectedOrder?.quantity}</p></div>
              <div><label>Borrowed Containers</label><p>{selectedOrder?.borrowed_containers}</p></div>
              <div><label>Container Status</label><p>{selectedOrder?.container_status}</p></div>
              <div><label>Payment Method</label><p>{selectedOrder?.payment_method}</p></div>
              <div><label>Order Type</label><p>{selectedOrder?.order_type}</p></div>
              <div><label>Status</label><span className={`StfOrd-status ${selectedOrder?.status?.toLowerCase()}`}>{selectedOrder?.status}</span></div>

              {selectedOrder?.payment_method === "GCash" && (
                <>
                  <div>
                    <label>Payment Status</label>
                    <span className={`StfOrd-status ${(selectedOrder?.payment_status || "pending").toLowerCase()}`}>
                      {selectedOrder?.payment_status || "Pending"}
                    </span>
                  </div>

                  {selectedOrder?.receipt_url && (
                    <div style={{ gridColumn: "1 / -1" }}>
                      <label>GCash Receipt</label>
                      <img
                        src={selectedOrder.receipt_url}
                        alt="GCash Receipt"
                        style={{
                          width: "100%",
                          maxWidth: "250px",
                          borderRadius: "10px",
                          border: "1px solid #e2e8f0",
                          marginTop: "6px",
                          display: "block",
                        }}
                      />
                    </div>
                  )}

                  {selectedOrder?.payment_status === "Pending" && (
                    <div style={{ gridColumn: "1 / -1", display: "flex", gap: "10px", marginTop: "10px" }}>
                      <button
                        onClick={() => updatePaymentStatus("Verified")}
                        style={{
                          flex: 1,
                          padding: "10px",
                          borderRadius: "8px",
                          border: "none",
                          background: "#22c55e",
                          color: "#fff",
                          fontWeight: 600,
                          cursor: "pointer",
                        }}
                      >
                        Verify Payment
                      </button>
                      <button
                        onClick={() => updatePaymentStatus("Rejected")}
                        style={{
                          flex: 1,
                          padding: "10px",
                          borderRadius: "8px",
                          border: "none",
                          background: "#ef4444",
                          color: "#fff",
                          fontWeight: 600,
                          cursor: "pointer",
                        }}
                      >
                        Reject Payment
                      </button>
                    </div>
                  )}
                </>
              )}
            </div>
            <div className="StfOrd-modal-actions">
              <button className="StfOrd-closeAction" onClick={() => setShowView(false)}>Close</button>
            </div>
          </div>
        </div>
      )}

      {/* EDIT MODAL */}
      {showEdit && (
        <div className="StfOrd-modal-overlay">
          <div className="StfOrd-edit-modal">
            <button className="StfOrd-close-btn" onClick={() => setShowEdit(false)}><X size={20} /></button>
            <h2>Edit Order</h2>
            <div className="StfOrd-form-group"><label>Order ID</label><input value={editData.order_code} disabled /></div>
            <div className="StfOrd-form-group"><label>Customer</label><input value={editData.full_name} onChange={(e) => setEditData({...editData, full_name: e.target.value})} /></div>
            <div className="StfOrd-form-group">
              <label>Order Type</label>
              <select value={editData.order_type} onChange={(e) => setEditData({...editData, order_type: e.target.value})}>
                <option value="Delivery">Delivery</option>
                <option value="Pickup">Pickup</option>
              </select>
            </div>
            {editData.order_type === "Delivery" && (
              <div className="StfOrd-form-group"><label>Date</label><input type="date" value={editData.delivery_date} onChange={(e) => setEditData({...editData, delivery_date: e.target.value})} /></div>
            )}
            <div className="StfOrd-form-group"><label>Quantity</label><input value={editData.quantity} disabled /></div>
            <div className="StfOrd-form-group">
              <label>Borrowed Containers</label>
              <input
                type="number"
                value={editData.borrowed_containers}
                onChange={(e) => setEditData({...editData, borrowed_containers: e.target.value})}
              />
            </div>
            <div className="StfOrd-form-group">
              <label>Container Status</label>
              <select value={editData.container_status} onChange={(e) => setEditData({...editData, container_status: e.target.value})}>
                <option value="Unreturned">Unreturned</option>
                <option value="Returned">Returned</option>
              </select>
            </div>
            <div className="StfOrd-form-group">
              <label>Payment Method</label>
              <select value={editData.payment_method} onChange={(e) => setEditData({...editData, payment_method: e.target.value})}>
                <option value="COD">COD</option>
                <option value="GCash">GCash</option>
                <option value="Card">Card</option>
              </select>
            </div>
            {editData.payment_method === "GCash" && (
              <div className="StfOrd-form-group">
                <label>Payment Status</label>
                <select value={editData.payment_status} onChange={(e) => setEditData({...editData, payment_status: e.target.value})}>
                  <option value="Pending">Pending</option>
                  <option value="Verified">Verified</option>
                  <option value="Rejected">Rejected</option>
                </select>
              </div>
            )}
            <div className="StfOrd-form-group">
              <label>Status</label>
              <select value={editData.status} onChange={(e) => setEditData({...editData, status: e.target.value})}>
                <option value="Pending">Pending</option>
                <option value="Processing">Processing</option>
                <option value="Delivered">Delivered</option>
              </select>
            </div>
            <div className="StfOrd-modal-actions">
              <button className="StfOrd-closeAction" onClick={() => setShowEdit(false)}>Cancel</button>
              <button className="StfOrd-save-btn" onClick={handleSaveChanges}>Save Changes</button>
            </div>
          </div>
        </div>
      )}

      {/* DELETE MODAL */}
      {showDelete && (
        <div className="StfOrd-modal-overlay">
          <div className="StfOrd-delete-modal">
            <button className="StfOrddelete-close-btn" onClick={() => setShowDelete(false)}><X size={20} /></button>
            <h1>Delete Order</h1>
            <h6>Are you sure you want to delete this order? This action cannot be undone.</h6>

            <div className="StfOrd-delete-details">
              <div>
                <label>Order ID</label>
                <p>{selectedOrder?.order_code}</p>
              </div>
              <div>
                <label>Customer</label>
                <p>{selectedOrder?.full_name}</p>
              </div>
              <div>
                <label>Item</label>
                <p>{selectedOrder?.item_name}</p>
              </div>
              <div>
                <label>Total Amount</label>
                <p>₱{selectedOrder?.total_amount}</p>
              </div>
              <div>
                <label>Status</label>
                <span className={`StfOrd-status ${selectedOrder?.status?.toLowerCase()}`}>
                  {selectedOrder?.status}
                </span>
              </div>
            </div>

            <div className="StfOrd-delete-actions">
              <button className="StfOrd-cancel-btn" onClick={() => setShowDelete(false)}>No, Cancel</button>
              <button className="StfOrd-confirm-delete" onClick={confirmDelete}>Delete Order</button>
            </div>
          </div>
        </div>
      )}

      {/* ADD MODAL */}
      {showAdd && (
        <div className="StfOrd-modal-overlay">
          <div className="StfOrd-add-modal">
            <button className="StfOrdAdd-close-btn" onClick={() => setShowAdd(false)}><X size={20} /></button>
            <h2>Add Order</h2>

            <div className="StfOrd-form-container">
              <div className="StfOrd-form-group">
                <label>Water Type</label>
                <input value="Purified" disabled style={{ backgroundColor: "#f3f4f6", cursor: "not-allowed" }} />
              </div>

              <div className="StfOrd-form-group">
                <label>Size / Variant</label>
                <select
                  value={addData.size_variant}
                  onChange={(e) => setAddData({ ...addData, size_variant: e.target.value })}
                >
                  <option value="">Select Size</option>
                  {inventoryStock.map((item) => {
                    const stock = Number(item.quantity_available || item.quantity || 0);
                    const isOut = stock <= 0;
                    const variantName = item.item_name;

                    return (
                      <option key={item.id || item.item_name} value={variantName} disabled={isOut}>
                        {variantName} {isOut ? "(Out of Stock)" : `(Stock: ${stock})`}
                      </option>
                    );
                  })}
                </select>
              </div>

              <div className="StfOrd-form-group">
                <label>Quantity</label>
                <input
                  type="number"
                  min="1"
                  value={addData.quantity}
                  onChange={(e) => setAddData({ ...addData, quantity: e.target.value })}
                  style={{
                    borderColor: is500mlDeliveryInvalid ? "#ef4444" : undefined
                  }}
                />
                {is500mlDeliveryInvalid && (
                  <span style={{
                    color: "#ef4444",
                    fontSize: "11px",
                    marginTop: "3px",
                    display: "block",
                    lineHeight: "1.2"
                  }}>
                    Minimum order for 500ml delivery is 12 pcs.
                  </span>
                )}
              </div>

              <div className="StfOrd-form-group">
                <label>Order Type</label>
                <select
                  value={addData.order_type}
                  onChange={(e) => setAddData({ ...addData, order_type: e.target.value })}
                >
                  <option value="Delivery">Delivery</option>
                  <option value="Pickup">Pickup</option>
                </select>
              </div>

              <div className="StfOrd-form-group">
                <label>Borrowed Containers (Qty)</label>
                <input
                  type="number"
                  min="0"
                  disabled={addData.order_type === "Pickup"}
                  value={addData.order_type === "Pickup" ? 0 : addData.borrowed_containers}
                  onChange={(e) => setAddData({ ...addData, borrowed_containers: e.target.value })}
                  style={{ backgroundColor: addData.order_type === "Pickup" ? "#f3f4f6" : "#fff", cursor: addData.order_type === "Pickup" ? "not-allowed" : "pointer" }}
                />
              </div>

              <div className="StfOrd-form-group">
                <label>Container Status</label>
                <select
                  disabled={addData.order_type === "Pickup"}
                  value={addData.order_type === "Pickup" ? "Unreturned" : addData.container_status}
                  onChange={(e) => setAddData({ ...addData, container_status: e.target.value })}
                  style={{ backgroundColor: addData.order_type === "Pickup" ? "#f3f4f6" : "#fff", cursor: addData.order_type === "Pickup" ? "not-allowed" : "pointer" }}
                >
                  <option value="Unreturned">Unreturned</option>
                  <option value="Returned">Returned</option>
                </select>
              </div>

              <div className="StfOrd-form-group">
                <label>Customer Name</label>
                <input
                  value={addData.full_name}
                  onChange={(e) => setAddData({ ...addData, full_name: e.target.value })}
                />
              </div>

              <div className="StfOrd-form-group">
                <label>Contact Number</label>
                <input
                  value={addData.contact_number}
                  onChange={(e) => setAddData({ ...addData, contact_number: e.target.value })}
                />
              </div>

              <div className="StfOrd-form-group">
                <label>Delivery Date</label>
                <input
                  type="date"
                  min={new Date().toISOString().split("T")[0]}
                  disabled={addData.order_type === "Pickup"}
                  value={addData.order_type === "Pickup" ? "" : addData.delivery_date}
                  onChange={(e) => setAddData({ ...addData, delivery_date: e.target.value })}
                  style={{ backgroundColor: addData.order_type === "Pickup" ? "#f3f4f6" : "#fff", cursor: addData.order_type === "Pickup" ? "not-allowed" : "pointer" }}
                />
              </div>

              <div className="StfOrd-form-group">
                <label>Delivery Address</label>
                <input
                  disabled={addData.order_type === "Pickup"}
                  value={addData.order_type === "Pickup" ? "N/A (Pickup Order)" : addData.delivery_address}
                  onChange={(e) => setAddData({ ...addData, delivery_address: e.target.value })}
                  style={{ backgroundColor: addData.order_type === "Pickup" ? "#f3f4f6" : "#fff", cursor: addData.order_type === "Pickup" ? "not-allowed" : "pointer" }}
                />
              </div>

              <div className="StfOrd-form-group">
                <label>Payment Method</label>
                <select
                  value={addData.payment_method}
                  onChange={(e) => setAddData({ ...addData, payment_method: e.target.value })}
                >
                  <option value="">Select payment method</option>
                  <option value="Card">Cash</option>
                  <option value="COD">Cash on Delivery</option>
                  <option value="GCash">GCash</option>
                </select>
              </div>

              <div className="StfOrd-form-group">
                <label>Total Amount {addData.order_type === "Delivery" && deliveryFee > 0 ? `(Inc. ₱${deliveryFee} Delivery Fee)` : ""}</label>
                <input value={`₱${totalAmount}`} disabled />
              </div>

              <div className="StfOrd-modal-actions">
                <button className="StfOrd-closeAction" onClick={() => setShowAdd(false)}>Cancel</button>
                <button className="StfOrd-save-btn" onClick={handleAddOrder}>Add Order</button>
              </div>
            </div>

          </div>
        </div>
      )}

    </div>
  );
}

export default StaffOrders;
