import { useState, useEffect, useRef } from "react";
import "./expenses.css";
import Table from "../../../components/Table";
import { supabase } from "../../../supabase";
import {
  Plus,
  Pencil,
  Trash2,
  AlertTriangle,
  Calendar,
  DollarSign,
  Layers,
  X,
  Download,
  CheckCircle,
  XCircle,
} from "lucide-react";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

// ==========================================
// EXPORT PDF FUNCTION (Expenses Template)
// ==========================================
export const exportExpensesToPDF = (expensesData, filename = "expenses-report.pdf", generatedBy = "System Admin") => {
  const doc = new jsPDF();

  const primaryColor = [30, 41, 59];
  const accentColor = [79, 70, 229];
  const lightBg = [248, 250, 252];

  // Header Design
  doc.setFillColor(...accentColor);
  doc.rect(14, 15, 3, 14, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.setTextColor(...primaryColor);
  doc.text("ADRENALINE AQUA WATER REFILLING STATION", 21, 22);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text("Expenses & Cash Outflow Report", 21, 28);

  doc.setFontSize(9);
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, 196, 22, { align: "right" });

  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.4);
  doc.line(14, 34, 196, 34);

  // Summary Box inside PDF
  const totalAmountSum = expensesData.reduce((sum, item) => sum + Number(item.amount || 0), 0);

  doc.setFillColor(...lightBg);
  doc.roundedRect(14, 40, 182, 14, 1.5, 1.5, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(...primaryColor);
  doc.text(`Total Records: ${expensesData.length}`, 18, 49);
  doc.text(`Total Outflow: ₱${totalAmountSum.toLocaleString(undefined, { minimumFractionDigits: 2 })}`, 110, 49);

  // Table Setup
  const tableColumn = ["Expense ID", "Date", "Category", "Description", "Amount"];
  const tableRows = expensesData.map((exp) => [
    exp.expenses_code || "—",
    new Date(exp.date).toLocaleDateString() || "—",
    exp.category || "—",
    exp.description || "—",
    `₱${Number(exp.amount || 0).toFixed(2)}`,
  ]);

  autoTable(doc, {
    head: [tableColumn],
    body: tableRows,
    startY: 60,
    theme: "striped",
    headStyles: {
      fillColor: primaryColor,
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 8,
      cellPadding: 6,
    },
    bodyStyles: {
      textColor: [51, 65, 85],
      fontSize: 8,
      cellPadding: 6,
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
    margin: { left: 14, right: 14 },
    didDrawPage: (data) => {
      const pageHeight = doc.internal.pageSize.height;
      doc.setFontSize(8);
      doc.setTextColor(148, 163, 184);
      doc.text(`Generated by: ${generatedBy}`, data.settings.margin.left, pageHeight - 10);
      doc.text(`Page ${doc.internal.getNumberOfPages()}`, doc.internal.pageSize.width - data.settings.margin.right, pageHeight - 10, { align: "right" });
    },
  });

  doc.save(filename);
};

function Expenses() {
  const [expenses, setExpenses] = useState([]);
  const [search, setSearch] = useState("");
  const [categoryFilter, setCategoryFilter] = useState("All");
  const [timeFilter, setTimeFilter] = useState("All");
  const [sortOrder, setSortOrder] = useState("latest");

  // MODALS CONTROL STATES
  const [showAdd, setShowAdd] = useState(false);
  const [showEdit, setShowEdit] = useState(false);
  const [showDelete, setShowDelete] = useState(false);
  const [selectedExpense, setSelectedExpense] = useState(null);

  // FORM STATES
  const [formData, setFormData] = useState({
    category: "Utilities",
    description: "",
    amount: "",
    date: new Date().toISOString().split("T")[0],
  });

  // ===============================
  // TOAST
  // ===============================
  const [toast, setToast] = useState({
    message: "",
    type: "success",
    show: false,
  });
  const toastTimer = useRef(null);

  const showToast = (message, type = "success") => {
    clearTimeout(toastTimer.current);
    setToast({ message, type, show: true });
    toastTimer.current = setTimeout(() => {
      setToast({ message: "", type: "success", show: false });
    }, 3000);
  };

  useEffect(() => {
    return () => clearTimeout(toastTimer.current);
  }, []);

  useEffect(() => {
    fetchExpenses();
  }, []);

  // FETCH FROM SUPABASE
  const fetchExpenses = async () => {
    const { data, error } = await supabase
      .from("expenses")
      .select("*")
      .order("date", { ascending: false });

    if (error) {
      console.error("Error fetching expenses:", error.message);
      showToast("Failed to load expenses: " + error.message, "error");
      return;
    }
    setExpenses(data || []);
  };

  // AUTOMATED CODE GENERATOR (EXP2026001)
  const generateExpenseCode = async () => {
    const year = new Date().getFullYear();
    const { data } = await supabase
      .from("expenses")
      .select("expenses_code")
      .like("expenses_code", `EXP${year}%`)
      .order("expenses_code", { ascending: false })
      .limit(1);

    let next = 1;
    if (data?.length > 0) {
      const last = data[0].expenses_code;
      next = Number(last.replace(`EXP${year}`, "")) + 1;
    }
    return `EXP${year}${String(next).padStart(3, "0")}`;
  };

  // ADD EXPENSE
  const handleAddExpense = async () => {
    if (!formData.description || !formData.amount || !formData.date) {
      showToast("Please fill in all required fields.", "error");
      return;
    }

    const code = await generateExpenseCode();

    const { error } = await supabase.from("expenses").insert([
      {
        expenses_code: code,
        category: formData.category,
        description: formData.description,
        amount: Number(formData.amount),
        date: formData.date,
      },
    ]);

    if (error) {
      showToast("Error adding expense: " + error.message, "error");
    } else {
      showToast("Expense recorded successfully!", "success");
      setShowAdd(false);
      resetForm();
      fetchExpenses();
    }
  };

  // EDIT EXPENSE
  const handleEditExpense = async () => {
    if (!formData.description || !formData.amount || !formData.date) {
      showToast("Please fill in all required fields.", "error");
      return;
    }

    const { error } = await supabase
      .from("expenses")
      .update({
        category: formData.category,
        description: formData.description,
        amount: Number(formData.amount),
        date: formData.date,
      })
      .eq("expenses_code", selectedExpense.expenses_code);

    if (error) {
      showToast("Update failed: " + error.message, "error");
    } else {
      showToast("Expense updated successfully!", "success");
      setShowEdit(false);
      fetchExpenses();
    }
  };

  // DELETE EXPENSE
  const handleDeleteExpense = async () => {
    const { error } = await supabase
      .from("expenses")
      .delete()
      .eq("expenses_code", selectedExpense.expenses_code);

    if (error) {
      showToast("Delete failed: " + error.message, "error");
    } else {
      showToast("Expense deleted successfully!", "success");
      setShowDelete(false);
      fetchExpenses();
    }
  };

  const resetForm = () => {
    setFormData({
      category: "Utilities",
      description: "",
      amount: "",
      date: new Date().toISOString().split("T")[0],
    });
  };

  // SUMMARY CARD CALCULATIONS
  const getSummaryTotals = () => {
    const now = new Date();
    let daily = 0, weekly = 0, monthly = 0;

    expenses.forEach((item) => {
      const expDate = new Date(item.date);
      const diffTime = Math.abs(now - expDate);
      const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));

      if (now.toDateString() === expDate.toDateString()) {
        daily += Number(item.amount || 0);
      }
      if (diffDays <= 7) {
        weekly += Number(item.amount || 0);
      }
      if (now.getMonth() === expDate.getMonth() && now.getFullYear() === expDate.getFullYear()) {
        monthly += Number(item.amount || 0);
      }
    });

    return { daily, weekly, monthly };
  };

  const totals = getSummaryTotals();

  // DYNAMIC BREAKDOWN FOR GRAPH & ACTIVITY
  const getCategoryBreakdown = () => {
    const breakdown = { Utilities: 0, Salary: 0, Maintenance: 0, Supplies: 0 };
    let totalAll = 0;

    expenses.forEach((item) => {
      if (breakdown[item.category] !== undefined) {
        breakdown[item.category] += Number(item.amount || 0);
        totalAll += Number(item.amount || 0);
      }
    });

    return { breakdown, totalAll };
  };

  const { breakdown, totalAll } = getCategoryBreakdown();

  // FILTER & SEARCH LOGIC
  const filteredItems = expenses
    .filter((item) => {
      const matchSearch =
        item.expenses_code?.toLowerCase().includes(search.toLowerCase()) ||
        item.description?.toLowerCase().includes(search.toLowerCase());

      const matchCategory = categoryFilter === "All" || item.category === categoryFilter;

      const now = new Date();
      const expDate = new Date(item.date);
      const diffDays = Math.ceil(Math.abs(now - expDate) / (1000 * 60 * 60 * 24));

      let matchTime = true;
      if (timeFilter === "Day") matchTime = now.toDateString() === expDate.toDateString();
      if (timeFilter === "Week") matchTime = diffDays <= 7;
      if (timeFilter === "Month") matchTime = now.getMonth() === expDate.getMonth() && now.getFullYear() === expDate.getFullYear();

      return matchSearch && matchCategory && matchTime;
    })
    .sort((a, b) => {
      if (sortOrder === "latest") return new Date(b.date) - new Date(a.date);
      if (sortOrder === "oldest") return new Date(a.date) - new Date(b.date);
      if (sortOrder === "highest") return b.amount - a.amount;
      if (sortOrder === "lowest") return a.amount - b.amount;
      return 0;
    });

  // EXPORT PDF (with toast)
  const handleExportPDF = () => {
    if (filteredItems.length === 0) {
      showToast("No expense records to export.", "error");
      return;
    }

    try {
      const savedUser = JSON.parse(localStorage.getItem("user")) || {};
      const userPosition = savedUser.position || savedUser.role || "Admin";
      const userName = savedUser.name || savedUser.fullName || "System Admin";
      const generatedByFull = `${userPosition} - ${userName}`;

      exportExpensesToPDF(filteredItems, "expenses-report.pdf", generatedByFull);
      showToast("Expenses report exported successfully!", "success");
    } catch (err) {
      console.error("Export error:", err);
      showToast("Failed to export expenses report.", "error");
    }
  };

  // TABLE COLUMNS CONFIGURATION
  const columns = [
    { key: "expenses_code", label: "Expense ID" },
    { key: "date", label: "Date", render: (row) => new Date(row.date).toLocaleDateString() },
    {
      key: "category",
      label: "Category",
      render: (row) => <span className="plain-category-text">{row.category}</span>
    },
    { key: "description", label: "Description" },
    { key: "amount", label: "Amount", render: (row) => `₱${Number(row.amount || 0).toFixed(2)}` },
    {
      key: "actions",
      label: "Action",
      render: (row) => (
        <div className="action-buttons">
          <button
            className="edit-icon-btn"
            onClick={() => {
              setSelectedExpense(row);
              setFormData({
                category: row.category,
                description: row.description,
                amount: row.amount,
                date: row.date ? String(row.date).slice(0, 10) : "",
              });
              setShowEdit(true);
            }}
          >
            <Pencil size={16} />
          </button>
          <button
            className="delete-icon-btn"
            onClick={() => {
              setSelectedExpense(row);
              setShowDelete(true);
            }}
          >
            <Trash2 size={16} />
          </button>
        </div>
      ),
    },
  ];

  return (
    <div className="expenses-page">
      {/* TOAST */}
      {toast.show && (
        <div className={`exp-toast ${toast.type}`}>
          <div className="exp-toast-icon">
            {toast.type === "success" ? (
              <CheckCircle size={20} />
            ) : (
              <XCircle size={20} />
            )}
          </div>
          <div className="exp-toast-text">{toast.message}</div>
        </div>
      )}

      {/* TITLE HEADER */}
      <div className="expenses-header">
        <div>
          <h1>Expenses</h1>
          <p>Real-time cash outflow tracking and category cost analysis</p>
        </div>
      </div>

      {/* DASHBOARD STATUS CARDS */}
      <div className="inventory-summary-cards">
        <div className="summary-card total-val">
          <Calendar className="card-icon" />
          <div>
            <h3>Today's Outflow</h3>
            <h2>₱{totals.daily.toLocaleString(undefined, { minimumFractionDigits: 2 })}</h2>
          </div>
        </div>
        <div className="summary-card total-val">
          <DollarSign className="card-icon" />
          <div>
            <h3>This Week</h3>
            <h2>₱{totals.weekly.toLocaleString(undefined, { minimumFractionDigits: 2 })}</h2>
          </div>
        </div>
        <div className="summary-card total-val">
          <Layers className="card-icon" />
          <div>
            <h3>This Month</h3>
            <h2>₱{totals.monthly.toLocaleString(undefined, { minimumFractionDigits: 2 })}</h2>
          </div>
        </div>
      </div>

      {/* SEARCH, FILTERS & ACTION ACTIONS */}
      <div className="controls-row">
        <div className="left-controls">
          <input
            type="text"
            className="search-input"
            placeholder="Search code or description..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
          />

          <select className="filter-select" value={categoryFilter} onChange={(e) => setCategoryFilter(e.target.value)}>
            <option value="All">All Categories</option>
            <option value="Utilities">Utilities</option>
            <option value="Salary">Salary</option>
            <option value="Maintenance">Maintenance</option>
            <option value="Supplies">Supplies</option>
          </select>

          <select className="filter-select" value={timeFilter} onChange={(e) => setTimeFilter(e.target.value)}>
            <option value="All">All Time Range</option>
            <option value="Day">Today</option>
            <option value="Week">This Week</option>
            <option value="Month">This Month</option>
          </select>

          <select className="filter-select" value={sortOrder} onChange={(e) => setSortOrder(e.target.value)}>
            <option value="latest">Latest Date</option>
            <option value="oldest">Oldest Date</option>
            <option value="highest">Highest Amount</option>
            <option value="lowest">Lowest Amount</option>
          </select>
        </div>

        <div className="right-controls" style={{ display: "flex", gap: "10px" }}>
          <button className="add-btn" onClick={() => { resetForm(); setShowAdd(true); }}>
            <Plus size={16} /> Record Expense
          </button>

          <button
            onClick={handleExportPDF}
            className="export-pdf-btn"
            style={{ display: "flex", alignItems: "center", gap: "6px", padding: "8px 12px", cursor: "pointer", background: "#334155", color: "#fff", border: "none", borderRadius: "6px" }}
          >
            <Download size={16} /> Export PDF
          </button>
        </div>
      </div>

      {/* RENDER TABLE */}
      <div className="table-container">
        <Table columns={columns} data={filteredItems} />
      </div>

      {/* BOTTOM SECTION: GRAPH BREAKDOWN & ACTIVITY */}
      <div className="expenses-bottom-layout">

        {/* LEFT: Expense Activity Logs */}
        <div className="expense-analysis-box">
          <h3>Recent Expense Activity</h3>
          <div className="activity-timeline-container">
            {expenses.slice(0, 4).map((item, idx) => (
              <div className="activity-timeline-item" key={idx}>
                <div className="timeline-badge-dot"></div>
                <div className="timeline-log-details">
                  <div className="timeline-meta">
                    <span className="log-code">{item.expenses_code}</span>
                    <span className="log-date">{new Date(item.date).toLocaleDateString()}</span>
                  </div>
                  <p className="log-desc">Spent <b>₱{Number(item.amount).toFixed(2)}</b> on {item.description}</p>
                </div>
              </div>
            ))}
            {expenses.length === 0 && <p className="placeholder-text">No data available yet</p>}
          </div>
        </div>

        {/* RIGHT: Category Breakdown Chart Component */}
        <div className="expense-analysis-box">
          <h3>Category Summary Chart</h3>
          <div className="chart-bars-wrapper">
            {Object.keys(breakdown).map((cat) => {
              const amount = breakdown[cat];
              const percentage = totalAll > 0 ? (amount / totalAll) * 100 : 0;
              return (
                <div className="chart-bar-row" key={cat}>
                  <div className="chart-label-group">
                    <span className="chart-cat-name">{cat}</span>
                    <span className="chart-cat-value">₱{amount.toLocaleString()} ({percentage.toFixed(0)}%)</span>
                  </div>
                  <div className="progress-bar-bg">
                    <div className={`progress-bar-fill fill-${cat.toLowerCase()}`} style={{ width: `${percentage}%` }}></div>
                  </div>
                </div>
              );
            })}
          </div>
        </div>

      </div>

      {/* ========================================== */}
      {/* MODAL: ADD EXPENSE                         */}
      {/* ========================================== */}
      {showAdd && (
        <div className="exp-modal-overlay" onClick={() => setShowAdd(false)}>
          <div className="exp-modal" onClick={(e) => e.stopPropagation()}>
            <div className="exp-modal-header">
              <div className="exp-modal-icon primary">
                <Plus size={22} />
              </div>
              <div className="exp-modal-titles">
                <h2>Record New Expense</h2>
                <p>Log a new cash outflow transaction.</p>
              </div>
              <button className="exp-modal-close" onClick={() => setShowAdd(false)}>
                <X size={18} />
              </button>
            </div>

            <div className="exp-modal-body">
              <div className="exp-field">
                <label>Category</label>
                <select
                  value={formData.category}
                  onChange={(e) => setFormData({ ...formData, category: e.target.value })}
                >
                  <option value="Utilities">Utilities</option>
                  <option value="Salary">Salary</option>
                  <option value="Maintenance">Maintenance</option>
                  <option value="Supplies">Supplies</option>
                </select>
              </div>

              <div className="exp-field">
                <label>Description / Particulars</label>
                <input
                  type="text"
                  placeholder="e.g., Meralco bill payment"
                  value={formData.description}
                  onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                />
              </div>

              <div className="exp-field-row">
                <div className="exp-field">
                  <label>Amount (₱)</label>
                  <input
                    type="number"
                    placeholder="0.00"
                    value={formData.amount}
                    onChange={(e) => setFormData({ ...formData, amount: e.target.value })}
                  />
                </div>
                <div className="exp-field">
                  <label>Transaction Date</label>
                  <input
                    type="date"
                    value={formData.date}
                    onChange={(e) => setFormData({ ...formData, date: e.target.value })}
                  />
                </div>
              </div>
            </div>

            <div className="exp-modal-footer">
              <button className="exp-btn ghost" onClick={() => setShowAdd(false)}>Cancel</button>
              <button className="exp-btn primary" onClick={handleAddExpense}>Save Transaction</button>
            </div>
          </div>
        </div>
      )}

      {/* ========================================== */}
      {/* MODAL: EDIT EXPENSE                        */}
      {/* ========================================== */}
      {showEdit && (
        <div className="exp-modal-overlay" onClick={() => setShowEdit(false)}>
          <div className="exp-modal" onClick={(e) => e.stopPropagation()}>
            <div className="exp-modal-header">
              <div className="exp-modal-icon primary">
                <Pencil size={20} />
              </div>
              <div className="exp-modal-titles">
                <h2>Edit Expense Log</h2>
                <p>Tracking voucher: <b>{selectedExpense?.expenses_code}</b></p>
              </div>
              <button className="exp-modal-close" onClick={() => setShowEdit(false)}>
                <X size={18} />
              </button>
            </div>

            <div className="exp-modal-body">
              <div className="exp-field">
                <label>Category</label>
                <select
                  value={formData.category}
                  onChange={(e) => setFormData({ ...formData, category: e.target.value })}
                >
                  <option value="Utilities">Utilities</option>
                  <option value="Salary">Salary</option>
                  <option value="Maintenance">Maintenance</option>
                  <option value="Supplies">Supplies</option>
                </select>
              </div>

              <div className="exp-field">
                <label>Description / Particulars</label>
                <input
                  type="text"
                  value={formData.description}
                  onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                />
              </div>

              <div className="exp-field-row">
                <div className="exp-field">
                  <label>Amount (₱)</label>
                  <input
                    type="number"
                    value={formData.amount}
                    onChange={(e) => setFormData({ ...formData, amount: e.target.value })}
                  />
                </div>
                <div className="exp-field">
                  <label>Transaction Date</label>
                  <input
                    type="date"
                    value={formData.date}
                    onChange={(e) => setFormData({ ...formData, date: e.target.value })}
                  />
                </div>
              </div>
            </div>

            <div className="exp-modal-footer">
              <button className="exp-btn ghost" onClick={() => setShowEdit(false)}>Cancel</button>
              <button className="exp-btn primary" onClick={handleEditExpense}>Update Log</button>
            </div>
          </div>
        </div>
      )}

      {/* ========================================== */}
      {/* MODAL: DELETE CONFIRMATION                 */}
      {/* ========================================== */}
      {showDelete && (
        <div className="exp-modal-overlay" onClick={() => setShowDelete(false)}>
          <div className="exp-modal sm" onClick={(e) => e.stopPropagation()}>
            <div className="exp-delete-body">
              <div className="exp-delete-icon">
                <AlertTriangle size={28} />
              </div>
              <h2>Delete Voucher</h2>
              <p className="exp-delete-text">
                Are you sure you want to delete this expense log? This will permanently remove the cash outflow record and will affect accounting summaries. This cannot be undone.
              </p>

              <div className="exp-details-box">
                <div className="exp-detail-row"><span>Voucher ID</span><b>{selectedExpense?.expenses_code}</b></div>
                <div className="exp-detail-row"><span>Category</span><b>{selectedExpense?.category}</b></div>
                <div className="exp-detail-row"><span>Particulars</span><b>{selectedExpense?.description}</b></div>
                <div className="exp-detail-row"><span>Amount Paid</span><b>₱{Number(selectedExpense?.amount || 0).toFixed(2)}</b></div>
                <div className="exp-detail-row"><span>Date</span><b>{selectedExpense?.date ? new Date(selectedExpense.date).toLocaleDateString() : "-"}</b></div>
              </div>
            </div>

            <div className="exp-modal-footer split">
              <button className="exp-btn ghost" onClick={() => setShowDelete(false)}>No, Cancel</button>
              <button className="exp-btn danger" onClick={handleDeleteExpense}>Delete Record</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

export default Expenses;
