import { useState, useEffect, useRef } from "react";
import "./sales.css";
import Table from "../../../components/Table";
import { supabase } from "../../../supabase";
import { Download } from "lucide-react";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Tooltip as ChartTooltip,
  Legend,
  Filler,
} from "chart.js";

ChartJS.register(
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  ChartTooltip,
  Legend,
  Filler
);

import { Line } from "react-chartjs-2";
import {
  Calendar,
  BarChart3,
  CalendarDays,
  PieChart,
  CheckCircle,
  XCircle,
} from "lucide-react";

// ==========================================
// EXPORT PDF FUNCTION (Sales Template)
// ==========================================
export const exportSalesToPDF = (salesData, filename = "sales-report.pdf", generatedBy = "System Admin") => {
  const doc = new jsPDF();

  const primaryColor = [30, 41, 59];
  const accentColor = [37, 99, 235];
  const lightBg = [248, 250, 252];

  // Header Design
  doc.setFillColor(...accentColor);
  doc.rect(14, 15, 3, 14, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.setTextColor(...primaryColor);
  doc.text("ADRENALINE AQUA WATER REFILLING STATION", 21, 22);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text("Sales Performance & Revenue Report", 21, 28);

  doc.setFontSize(9);
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, 196, 22, { align: "right" });

  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.4);
  doc.line(14, 34, 196, 34);

  // Summary Box inside PDF
  const totalSalesSum = salesData.reduce((sum, item) => {
    // Alisin ang currency symbol at commas kung meron man para makwenta nang tama
    const cleanNum = Number(String(item.totalSales || 0).replace(/[^\d.-]/g, ""));
    return sum + cleanNum;
  }, 0);

  doc.setFillColor(...lightBg);
  doc.roundedRect(14, 40, 182, 14, 1.5, 1.5, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(...primaryColor);
  doc.text(`Total Records: ${salesData.length}`, 18, 49);
  doc.text(`Total Revenue: ₱${totalSalesSum.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`, 110, 49);

  // Table Setup
  const tableColumn = ["Sales ID", "Date", "Total Products", "Payment Method", "Total Sales"];
  const tableRows = salesData.map((item) => [
    item.salesId || "—",
    item.date || "—",
    item.totalProducts ?? 0,
    item.paymentMethod || "—",
    item.totalSales.startsWith("₱") ? item.totalSales : `₱${item.totalSales}`,
  ]);

  autoTable(doc, {
    head: [tableColumn],
    body: tableRows,
    startY: 60,
    theme: "striped",
    headStyles: {
      fillColor: primaryColor,
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 8,
      cellPadding: 6,
    },
    bodyStyles: {
      textColor: [51, 65, 85],
      fontSize: 8,
      cellPadding: 6,
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
    margin: { left: 14, right: 14 },
    didDrawPage: (data) => {
      const pageHeight = doc.internal.pageSize.height;
      doc.setFontSize(8);
      doc.setTextColor(148, 163, 184);
      doc.text(`Generated by: ${generatedBy}`, data.settings.margin.left, pageHeight - 10);
      doc.text(`Page ${doc.internal.getNumberOfPages()}`, doc.internal.pageSize.width - data.settings.margin.right, pageHeight - 10, { align: "right" });
    },
  });

  doc.save(filename);
};

function Sales() {
  const [sales, setSales] = useState([]);
  const [monthlySales, setMonthlySales] = useState([]);
  const [search, setSearch] = useState("");
  const [paymentFilter, setPaymentFilter] = useState("All");

  const [stats, setStats] = useState({
    today: 0,
    weekly: 0,
    monthly: 0,
    overall: 0,
  });

  // ===============================
  // TOAST
  // ===============================
  const [toast, setToast] = useState({
    message: "",
    type: "success",
    show: false,
  });
  const toastTimer = useRef(null);

  const showToast = (message, type = "success") => {
    clearTimeout(toastTimer.current);
    setToast({ message, type, show: true });
    toastTimer.current = setTimeout(() => {
      setToast({ message: "", type: "success", show: false });
    }, 3000);
  };

  useEffect(() => {
    return () => clearTimeout(toastTimer.current);
  }, []);

  useEffect(() => {
    fetchSales();
  }, []);

  const fetchSales = async () => {
    const { data, error } = await supabase
      .from("sales")
      .select(`
        sales_code,
        date,
        total_products,
        total_sales,
        payment_method
      `)
      .order("date", { ascending: false });

    if (error) {
      console.log(error.message);
      showToast("Failed to load sales: " + error.message, "error");
      return;
    }

    const now = new Date();
    const startOfToday = new Date(now.getFullYear(), now.getMonth(), now.getDate());
    const startOfWeek = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);
    const startOfMonth = new Date(now.getFullYear(), now.getMonth(), 1);

    let todaySum = 0;
    let weeklySum = 0;
    let monthlySum = 0;
    let overallSum = 0;

    (data || []).forEach((sale) => {
      const saleAmount = Number(sale.total_sales || 0);
      overallSum += saleAmount;

      if (sale.date) {
        const saleDate = new Date(sale.date);
        if (saleDate >= startOfToday) todaySum += saleAmount;
        if (saleDate >= startOfWeek) weeklySum += saleAmount;
        if (saleDate >= startOfMonth) monthlySum += saleAmount;
      }
    });

    setStats({
      today: todaySum,
      weekly: weeklySum,
      monthly: monthlySum,
      overall: overallSum,
    });

    const formatted = (data || []).map((sale) => {
      return {
        salesId: sale.sales_code,
        date: sale.date ? new Date(sale.date).toLocaleDateString() : "-",
        totalProducts: Number(sale.total_products || 0),
        totalSales: `₱${Number(sale.total_sales || 0).toLocaleString()}`,
        paymentMethod: sale.payment_method || "-",
      };
    });

    setSales(formatted);

    const months = [
      "Jan", "Feb", "Mar", "Apr", "May", "Jun",
      "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
    ];

    const grouped = {};
    months.forEach((month) => {
      grouped[month] = 0;
    });

    (data || []).forEach((sale) => {
      if (!sale.date) return;
      const month = new Date(sale.date).toLocaleString("en-US", {
        month: "short",
      });
      if (grouped[month] !== undefined) {
        grouped[month] += Number(sale.total_sales || 0);
      }
    });

    const graphData = months.map((month) => ({
      month,
      sales: grouped[month],
    }));

    setMonthlySales(graphData);
  };

  const filtered = sales.filter((item) => {
    const matchSearch = item.salesId?.toLowerCase().includes(search.toLowerCase());
    const matchPayment = paymentFilter === "All" || item.paymentMethod === paymentFilter;
    return matchSearch && matchPayment;
  });

  // ===============================
  // EXPORT PDF (with toast)
  // ===============================
  const handleExportPDF = () => {
    if (filtered.length === 0) {
      showToast("No sales records to export.", "error");
      return;
    }

    try {
      const savedUser = JSON.parse(localStorage.getItem("user")) || {};
      const userPosition = savedUser.position || savedUser.role || "Admin";
      const userName = savedUser.name || savedUser.fullName || "System Admin";
      const generatedByFull = `${userPosition} - ${userName}`;

      exportSalesToPDF(filtered, "sales-report.pdf", generatedByFull);
      showToast("Sales report exported successfully!", "success");
    } catch (err) {
      console.error("Export error:", err);
      showToast("Failed to export sales report.", "error");
    }
  };

  const columns = [
    { key: "salesId", label: "Sales ID" },
    { key: "date", label: "Date" },
    { key: "totalProducts", label: "Total Products" },
    { key: "totalSales", label: "Total Sales" },
    { key: "paymentMethod", label: "Payment Method" },
  ];

  const lineData = {
    labels: monthlySales.map(item => item.month),
    datasets: [
      {
        label: "Monthly Sales",
        data: monthlySales.map(item => item.sales),
        borderColor: "#2563eb",
        backgroundColor: (context) => {
          const chart = context.chart;
          const { ctx, chartArea } = chart;
          if (!chartArea) return null;
          const gradient = ctx.createLinearGradient(
            0, chartArea.top, 0, chartArea.bottom
          );
          gradient.addColorStop(0, "rgba(37,99,235,.35)");
          gradient.addColorStop(1, "rgba(147,197,253,0)");
          return gradient;
        },
        fill: true,
        tension: 0.35,
        borderWidth: 3,
        pointStyle: "circle",
        pointRadius: 7,
        pointHoverRadius: 10,
        pointBackgroundColor: "#93c5fd",
        pointBorderColor: "#2563eb",
        pointBorderWidth: 2,
        pointHoverBackgroundColor: "#ffffff",
        pointHoverBorderColor: "#2563eb",
        pointHoverBorderWidth: 3,
      },
    ],
  };

  const lineOptions = {
    responsive: true,
    maintainAspectRatio: false,
    interaction: {
      mode: "index",
      intersect: false,
    },
    plugins: {
      legend: {
        display: false,
      },
      tooltip: {
        backgroundColor: "#1e293b",
        titleColor: "#fff",
        bodyColor: "#fff",
        padding: 12,
        cornerRadius: 10,
        callbacks: {
          label: (context) => `₱${Number(context.raw).toLocaleString()}`,
        },
      },
    },
    scales: {
      x: {
        grid: {
          display: false,
        },
        ticks: {
          autoSkip: false,
          maxRotation: 0,
          minRotation: 0,
          font: {
            size: 11,
          },
        },
      },
      y: {
        beginAtZero: true,
        ticks: {
          callback: (value) => `₱${value}`,
        },
      },
    },
  };

  return (
    <div className="sales-page">
      {/* TOAST */}
      {toast.show && (
        <div className={`sales-toast ${toast.type}`}>
          <div className="sales-toast-icon">
            {toast.type === "success" ? (
              <CheckCircle size={20} />
            ) : (
              <XCircle size={20} />
            )}
          </div>
          <div className="sales-toast-text">{toast.message}</div>
        </div>
      )}

      {/* HEADER SECTION */}
      <div className="sales-header">
        <h1>Sales</h1>
        <p>Monitor daily and monthly sales performance</p>
      </div>

      {/* 💳 OVERVIEW CARDS */}
      <div className="sales-cards-container">
        <div className="sales-card card-today">
          <div className="icon-wrapper">
            <Calendar size={24} />
          </div>
          <div className="card-info">
            <span className="card-label">Today Sales</span>
            <h2 className="card-value">₱{stats.today.toLocaleString()}</h2>
          </div>
        </div>

        <div className="sales-card card-weekly">
          <div className="icon-wrapper">
            <BarChart3 size={24} />
          </div>
          <div className="card-info">
            <span className="card-label">Weekly Sales</span>
            <h2 className="card-value">₱{stats.weekly.toLocaleString()}</h2>
          </div>
        </div>

        <div className="sales-card card-monthly">
          <div className="icon-wrapper">
            <CalendarDays size={24} />
          </div>
          <div className="card-info">
            <span className="card-label">Monthly Sales</span>
            <h2 className="card-value">₱{stats.monthly.toLocaleString()}</h2>
          </div>
        </div>

        <div className="sales-card card-overall">
          <div className="icon-wrapper">
            <PieChart size={24} />
          </div>
          <div className="card-info">
            <span className="card-label">Overall Sales</span>
            <h2 className="card-value">₱{stats.overall.toLocaleString()}</h2>
          </div>
        </div>
      </div>

      {/* CONTROLS SECTION */}
      <div className="controls-row">
        <input
          type="text"
          className="search-input"
          placeholder="Search sales ID..."
          value={search}
          onChange={(e) => setSearch(e.target.value)}
        />

        <select
          className="filter-select"
          value={paymentFilter}
          onChange={(e) => setPaymentFilter(e.target.value)}
        >
          <option value="All">All Payment</option>
          <option value="COD">COD</option>
          <option value="GCash">GCash</option>
          <option value="Card">Card</option>
        </select>

        <button
          onClick={handleExportPDF}
          className="export-pdf-btn"
          style={{
            display: "flex",
            alignItems: "center",
            gap: "6px",
            padding: "10px 16px",
            cursor: "pointer",
            background: "#334155",
            color: "#fff",
            border: "none",
            borderRadius: "8px",
            fontWeight: "600",
            fontSize: "14px",
            height: "41px"
          }}
        >
          <Download size={16} /> Export PDF
        </button>
      </div>

      {/* DATA TABLE */}
      <div className="table-container">
        <Table columns={columns} data={filtered} emptyMessage="No sales records yet." />
      </div>

      {/* MONTHLY PERFORMANCE GRAPH */}
      <div className="sales-bottom">
        <div className="sales-graph-card">
          <h3 className="graph-title">Monthly Sales Revenue</h3>

          {monthlySales.length > 0 ? (
            <div style={{ width: "100%", height: "320px" }}>
              <Line data={lineData} options={lineOptions} />
            </div>
          ) : (
            <div className="graph-placeholder">
              No sales yet
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

export default Sales;
