import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export const exportToPDF = (deliveries, filename = "delivery-report.pdf", generatedBy = "System Admin") => {
  const doc = new jsPDF();

  // Modern Color Palette (Slate & Indigo theme)
  const primaryColor = [30, 41, 59];   // Slate 800 (Dark modern gray/blue)
  const accentColor = [79, 70, 229];   // Indigo 600 (Modern tech accent)
  const lightBg = [248, 250, 252];       // Slate 50 (Soft background)

  // 1. MODERN HEADER (Minimalist na may accent bar sa kaliwa)
  doc.setFillColor(...accentColor);
  doc.rect(14, 15, 3, 14, "F"); // Accent vertical line

  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.setTextColor(...primaryColor);
  doc.text("ADRENALINE AQUA WATER REFILLING STATION", 21, 22);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139); // Slate 500 (Subdued text)
  doc.text("Delivery Performance & Status Report", 21, 28);

  // Petsa sa kanang bahagi
  doc.setFontSize(9);
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, 196, 22, { align: "right" });

  // Thin minimalist divider line
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.4);
  doc.line(14, 34, 196, 34);

  // 2. SUMMARY METRICS BOX (Parang modern dashboard cards)
  const total = deliveries.length;
  const pending = deliveries.filter(d => d.status === 'Pending').length;
  const outForDelivery = deliveries.filter(d => d.status === 'Out for Delivery').length;
  const delivered = deliveries.filter(d => d.status === 'Delivered').length;

  doc.setFillColor(...lightBg);
  doc.roundedRect(14, 40, 182, 14, 1.5, 1.5, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(...primaryColor);
  doc.text(`Total: ${total}`, 20, 49);
  doc.text(`Pending: ${pending}`, 65, 49);
  doc.text(`Out for Delivery: ${outForDelivery}`, 115, 49);
  doc.text(`Delivered: ${delivered}`, 165, 49);

  // 3. TABLE DATA SETUP
  const tableColumn = ["Delivery ID", "Order ID", "Customer", "Address", "Date", "Status", "Rider"];
  const tableRows = deliveries.map((d) => [
    d.deliveryId || "—",
    d.orderId || "—",
    d.customer || "—",
    d.address || "—",
    d.date || "—",
    d.status || "—",
    d.rider || "Not Assigned",
  ]);

  // 4. MODERN TABLE STYLING (Striped theme, malinis na padding, modern fonts)
  autoTable(doc, {
    head: [tableColumn],
    body: tableRows,
    startY: 60,
    theme: "striped", // Modern striped design
    headStyles: {
      fillColor: primaryColor,
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 8,
      cellPadding: 6,
    },
    bodyStyles: {
      textColor: [51, 65, 85], // Slate 700
      fontSize: 8,
      cellPadding: 6,
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
    margin: { left: 14, right: 14 },
    didDrawPage: (data) => {
      // Modern Footer (Generated by sa kaliwa at Page number sa kanang ibaba)
      const pageHeight = doc.internal.pageSize.height;
      doc.setFontSize(8);
      doc.setTextColor(148, 163, 184);

      // Kaliwa: Pangalan ng nag-generate
      doc.text(`Generated by: ${generatedBy}`, data.settings.margin.left, pageHeight - 10);

      // Kanan: Page number
      doc.text(
        `Page ${doc.internal.getNumberOfPages()}`,
        doc.internal.pageSize.width - data.settings.margin.right,
        pageHeight - 10,
        { align: "right" }
      );
    },
  });

  // I-save ang file
  doc.save(filename);
};